FROM eclipse-temurin:21
LABEL org.opencontainers.image.authors="Thomas Bassler <thomas.bassler@drbassler.de>"
ENTRYPOINT ["java", "-jar", "/usr/share/proseo-facility-mgr/proseo-facility-mgr.jar"]

ADD target/proseo-facility-mgr.jar /usr/share/proseo-facility-mgr/proseo-facility-mgr.jar