#%RAML 1.0
title: prosEO Geotools REST Services API
version: v0.1
protocols: [ HTTP, HTTPS ] 
baseUri: /proseo/geotools/{version}
mediaType: application/json

types:
  RestId: !include ../../../../../interfaces/src/main/resources/raml/types/id.raml
  RestPoint: !include ../../../../../geotools/src/main/resources/raml/types/point.raml
  RestPolygon: !include ../../../../../geotools/src/main/resources/raml/types/polygon.raml

resourceTypes:
  standard:
    get?:
      responses:
        400:
          description: |
            The request sent to the server contains invalid data
          headers:
            Warning: !include types/error.raml
        500:
          description: |
            The requested was valid but the implementation is pending or an error occured                  
          headers:
            Warning: !include types/error.raml

/info:
  type: standard
  get:
    description: | 
      Get information about known region types
    displayName: getInfo
    responses:
      200:
        body:
          text/plain:
/contains:
  type: standard
  get:
    description: | 
      Tests whether the polygon is completly contained in any region of type(s)
    displayName: contains
    queryParameters:
      poly: 
        type: number[]
        description: String array containing latitude (uneven fields)/longitude (uneven fields) pairs in Double format, which together describe an area to be compared to a number of specified regions
      type?: 
        type: string[]
        description: String array used to determine which regions (specified in application.yml) to check. If the array parameter is null or empty, all available region types will be considered.
    responses:
      200:
        body:
          type: boolean
          example: true 
  post:
    description: |
      Tests whether the polygon is completly contained in any region of type(s) 
    displayName: containspoly
    queryParameters:
      type?: 
        type: string[]
        description: String array used to determine which regions (specified in application.yml) to check. If the array parameter is null or empty, all available region types will be considered.
    body:
      application/json:
        type: RestPolygon
        example: !include ../../../../../geotools/src/main/resources/raml/examples/polygon.json
    responses:
      200:
        body:
          type: boolean
          example: true 
/overlaps:
  type: standard
  get:
    description: |
      Tests whether the polygon is overlaps any region of type(s) 
    displayName: overlaps
    queryParameters:
      poly: 
        type: number[]
        description: String array containing latitude (uneven fields)/longitude (uneven fields) pairs in Double format, which together describe an area to be compared to a number of specified regions
      type?: 
        type: string[]
        description: String array used to determine which regions (specified in application.yml) to check. If the array parameter is null or empty, all available region types will be considered.
    responses:
      200:
        body:
          type: boolean
          example: true 
  post:
    description: |
      Tests whether the polygon is overlaps any region of type(s) 
    displayName: overlapspoly
    queryParameters: 
      type?: 
        type: string[]
        description: String array used to determine which regions (specified in application.yml) to check. If the array parameter is null or empty, all available region types will be considered.
    body:
      application/json:
        type: RestPolygon
        example: !include ../../../../../geotools/src/main/resources/raml/examples/polygon.json
    responses:
      200:
        body:
          type: boolean
          example: true