#%RAML 1.0
title: prosEO Order Manager REST Services API
version: v0.1
protocols: [ HTTPS ] 
baseUri: /proseo/order-mgr/{version}
mediaType: application/json

securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for
                 basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password"
                       credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.

types:
  Order: !include ../../../../../model/src/main/resources/raml/types/order.raml
  Parameter: !include ../../../../../model/src/main/resources/raml/types/parameter.raml
  Mission: !include ../../../../../model/src/main/resources/raml/types/mission.raml
  Orbit: !include ../../../../../model/src/main/resources/raml/types/orbit.raml

resourceTypes:
  standard:
    get?:
      responses:          
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        404:
          description: |
            The requested resource was not found                     
          headers:
            Warning: !include types/error.raml
    put?:
      responses:          
        404:
          description: |
            The requested resource on which the modification is being attempted was not found              
          headers:
            Warning: !include types/error.raml
    delete?:
      responses:          
        404:
          description: | 
            The requested resource to delete was not found 
          headers:
            Warning: !include types/error.raml
              
/orders:
  type: standard
  get:
    description: Get orders by mission, user-defined identifier, requested product classes or start time range
    queryParameters:
      mission?: string
      identifier?: string
      productClasses?: string[]
      startTimeFrom?: datetime
      startTimeTo?: datetime
    responses:
      200:
        body:
          application/json:
            type: Order[]
            example: !include ../../../../../model/src/main/resources/raml/examples/order-list.json
  post:
    description: Create a new order
    body:
      application/json:
        type: Order
        example: !include ../../../../../model/src/main/resources/raml/examples/order.json
    responses:
      201:
        body:
          application/json:
            type: Order
            example: !include ../../../../../model/src/main/resources/raml/examples/order.json
  /{id}:
    uriParameters:
      id:
        type: integer
        format: long
    get:
      description: Get a processing order by ID
      responses:
        200:
          body:
            application/json:
              type: Order
              example: !include ../../../../../model/src/main/resources/raml/examples/order.json
    put:
      description: Update a processing order by ID
      body:
        application/json:
          type: Order
          example: !include ../../../../../model/src/main/resources/raml/examples/order.json
      responses:
        200:
          body:
            application/json:
              type: Order
              example: !include ../../../../../model/src/main/resources/raml/examples/order.json
    delete:
      description: Delete a processing order by ID
      responses:
        204:
/missions:
  type: standard
  get:
    description: Get all missions
    responses:
      200:
        body:
          application/json:
            type: Mission[]
            example: !include ../../../../../model/src/main/resources/raml/examples/mission-list.json
  post:
    description: Create a new mission
    body:
      application/json:
        type: Mission
        example: !include ../../../../../model/src/main/resources/raml/examples/mission.json
    responses:
      201:
        body:
          application/json:
            type: Mission
            example: !include ../../../../../model/src/main/resources/raml/examples/mission.json
  /{id}:
    uriParameters:
      id:
        type: integer
        format: long
    get:
      description: Get a mission by ID
      responses:
        200:
          body:
            application/json:
              type: Mission
              example: !include ../../../../../model/src/main/resources/raml/examples/mission.json
    put:
      description: Update a mission by ID (including changes to the spacecraft list)
      body:
        application/json:
          type: Mission
          example: !include ../../../../../model/src/main/resources/raml/examples/mission.json
      responses:
        200:
          body:
            application/json:
              type: Mission
              example: !include ../../../../../model/src/main/resources/raml/examples/mission.json
    delete:
      description: Delete a mission by ID
      responses:
        204:
/orbits:
  type: standard
  get:
    description: Get orbits for a specific mission and spacecraft;
        if both an orbit number range and a time frame are set, the orbit range takes precedence
    queryParameters:
      missionCode: string
      spacecraftCode: string
      orbitNumberFrom?: integer
      orbitNumberTo?: integer
      starttimefrom?: datetime
      starttimeto?: datetime
    responses:
      200:
        body:
          application/json:
            type: Orbit[]
            example: !include ../../../../../model/src/main/resources/raml/examples/orbit-list.json
  post:
    description: Create new orbits
    body:
      application/json:
        type: Orbit[]
        example: !include ../../../../../model/src/main/resources/raml/examples/orbit-list.json
    responses:
      201:
        body:
          application/json:
            type: Orbit[]
            example: !include ../../../../../model/src/main/resources/raml/examples/orbit-list.json
  /{id}:
    uriParameters:
      id:
        type: integer
        format: long
    get:
      description: Get an orbit by ID
      responses:
        200:
          body:
            application/json:
              type: Orbit
              example: !include ../../../../../model/src/main/resources/raml/examples/orbit.json
    put:
      description: Update an orbit by ID
      body:
        application/json:
          type: Orbit
          example: !include ../../../../../model/src/main/resources/raml/examples/orbit.json
      responses:
        200:
          body:
            application/json:
              type: Mission
              example: !include ../../../../../model/src/main/resources/raml/examples/mission.json
    delete:
      description: Delete an orbit by ID
      responses:
        204:
