---
- name: Install kubectl configuration for various users
  include_tasks: install.yml
  vars:
    user: "{{ item }}"
  loop: "{{ kubectl_users }}"

- name: Create kubectl bindir, if it does not exist
  file:
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Copy kubectl
  copy:
    src: "{{ inventory_dir }}/bin/kubectl"
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0755
