FROM localhost:5000/proseo-facility-mgr:0.8.1
ADD application.yml /usr/share/proseo-facility-mgr/application.yml
ADD logback.xml /usr/share/proseo-facility-mgr/logback.xml
WORKDIR /usr/share/proseo-facility-mgr/
