#%RAML 1.0
title: prosEO User Manager REST Services API
version: v0.1
protocols: [ HTTPS ] 
baseUri: /proseo/user-mgr/{version}
mediaType: application/json

securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password" credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.

types:
  RestUser: !include ../../../../../model/src/main/resources/raml/types/user.raml
  RestGroup: !include ../../../../../model/src/main/resources/raml/types/group.raml
  RestQuota: !include ../../../../../model/src/main/resources/raml/types/quota.raml

resourceTypes:
  standard:
    get?:
      responses:          
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
    post?:
      responses:      
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
    patch?:
      responses:
        304:
          description: |
            No modification occurred, as the input and database data were equal
          headers:
            Warning: !include types/error.raml          
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        404:
          description: |
            No entity with the given ID exists.
          headers:
            Warning: !include types/error.raml
        409:
          description: |
            The entity has been modified since retrieval by the client.
          headers:
            Warning: !include types/error.raml
    delete?:
      responses: 
        304:
          description: |
            The deletion was unsuccessful
          headers:
            Warning: !include types/error.raml                   
        404:
          description: | 
            The requested resource to delete was not found 
          headers:
            Warning: !include types/error.raml

/login:
  type: standard
  get:
    description: |
      Let a user log in to a specific mission (the user is retrieved from the basic
      authentication information). Mission may be empty for the "root" user.
    displayName: login
    queryParameters:
      mission?: 
        type: string
        description: the mission code
    responses:
      200:
        body:
          application/json:
            type: string[]
            description: A list of authorities granted to the user for the given mission
      401:
        description: |
          If the user is not authorized for some reason, such as an expired password.
        headers:
          Warning: !include types/error.raml
      404:
        description: |
          The requested resource was not found                     
        headers:
          Warning: !include types/error.raml
            
/users:
  type: standard
  get:
    description: |
      Get users by mission (may be null, if root user sends request)
    displayName: getUsers
    queryParameters:
      mission?: 
        type: string
        description: the mission code
      recordFrom?: 
        type: integer
        format: int32
        description: the first result to return
      recordTo?:
        type: integer
        format: int32
        description: the last result to return
    responses:
      200:
        body:
          application/json:
            type: RestUser[]
            example: !include examples/user-list.json
      404:
        description: |
          The requested resource was not found                     
        headers:
          Warning: !include types/error.raml
      429:
        description: |
          The result list length exceeds a configured maximum.
        headers:
          Warning: !include types/error.raml
  post:
    description: |
      Create a new user
    displayName: createUser
    body:
      application/json:
        type: RestUser
        example: !include examples/user.json
    responses:
      201:
        body:
          application/json:
            type: RestUser
            example: !include examples/user.json
  /count:
    get:
      description: |
        Count the users matching the specified mission.
      displayName: countUsers
      queryParameters:
        missionCode?: 
          type: string
          description: the mission code
      responses:
        200:
          body:
            text/plain:
  /{username}:
    uriParameters:
      username: 
        type: string
        description: the user name
    get:
      description: |
        Get a user by name
      displayName: getUserByName
      responses:
        200:
          body:
            application/json:
              type: RestUser
              example: !include examples/user.json
        404:
          description: |
            The requested resource was not found                     
          headers:
            Warning: !include types/error.raml
        401:
          description: |
            A user attempted to access the data of another user.
          headers:
            Warning: !include types/error.raml
    patch:
      description: |
        Update a user by name
      displayName: modifyUser
      body:
        application/json:
          type: RestUser
          example: !include examples/user.json
      responses:
        200:
          body:
            application/json:
              type: RestUser
              example: !include examples/user.json
        401:
          description: |
            A user attempted to access the data of another user.
          headers:
            Warning: !include types/error.raml
    delete:
      description: |
        Delete a user by user name
      displayName: deleteUserByName
      responses:
        204:

/groups:
  type: standard
  get:
    description: |
      Get user groups by mission and optionally by group name
    displayName: getGroups
    queryParameters:
      mission: 
        type: string
        description: the mission code
      groupName?: 
        type: string
        description: the name of the user group
      recordFrom?: 
        type: integer
        format: int32
        description: the first result to return
      recordTo?:
        type: integer
        format: int32
        description: the last result to return
    responses:
      200:
        body:
          application/json:
            type: RestGroup[]
            example: !include examples/group-list.json
      404:
        description: |
          The requested resource was not found                     
        headers:
          Warning: !include types/error.raml
      429:
        description: |
          The result list length exceeds a configured maximum.
        headers:
          Warning: !include types/error.raml
  post:
    description: |
      Create a new user group
    displayName: createGroup
    body:
      application/json:
        type: RestGroup
        example: !include examples/group.json
    responses:
      201:
        body:
          application/json:
            type: RestGroup
            example: !include examples/group.json
  /count:
    get:
      description: |
        Count the user groups matching the specified mission
      displayName: countGroups
      queryParameters:
        missionCode: 
          type: string
          description: the mission code
      responses:
        200:
          body:
            text/plain:
  /{id}:
    uriParameters:
      id:
        type: integer
        format: long
        description: the user group ID
    get:
      description: |
        Get a user group by ID
      displayName: getGroupById
      responses:
        200:
          body:
            application/json:
              type: RestGroup
              example: !include examples/group.json
        404:
          description: |
            The requested resource was not found                     
          headers:
            Warning: !include types/error.raml
    patch:
      description: |
        Update a user group by ID
      displayName: modifyGroup
      body:
        application/json:
          type: RestGroup
          example: !include examples/group.json
      responses:
        200:
          body:
            application/json:
              type: RestGroup
              example: !include examples/group.json
    delete:
      description: |
        Delete a user group by ID
      displayName: deleteGroupById
      responses:
        204:
    /members:
      get:
        description: |
          Get all members of the given user group
        displayName: getGroupMembers
        responses:
          200:
            body:
              application/json:
                type: RestUser[]
                description: The list of users in this group        
          404:
            description: |
              The group has no members                   
            headers:
              Warning: !include types/error.raml
      post:
        description: |
          Add a member to the given user group
        displayName: addGroupMember
        queryParameters:
          username:
            type: string
            description: The name of the user to add
        responses:
          201:
            body:
              application/json:
                type: RestUser[]
                description: The list of users in this group (after addition)
          304:
            description: |
              No modification occurred, as the input and database data were equal
            headers:
              Warning: !include types/error.raml          
          404:
            description: |
              No entity with the given ID exists.
            headers:
              Warning: !include types/error.raml
      delete:
        description: |
          Delete a member from the given user group
        displayName: removeGroupMember
        queryParameters:
          username:
            type: string
            description: The name of the user to remove
        responses:
          204: