#%RAML 1.0 DataType
#  CscContentDate:
    type: object
    properties:
      Start:
        type: string
        description: Sensing start time of the input product
        pattern: ^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d.\d{3}Z$
      End:
        type: string
        description: Sensing stop time of the input product
        pattern: ^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d.\d{3}Z$
