#%RAML 1.0 DataType
#  CscInputProductReference:
    type: object
    properties:
      Reference?:
        type: string
        description: The file name of the input product to retrieve
      ContentDate?:
        type: CscContentDate
        description: The sensing range period
