#%RAML 1.0 DataType
#  OAuth2Response:
    type: object
    properties:
      access_token:
        type: string
        description: The access token issued by the authorization server (as per RFC 6749)
      token_type:
        type: string
        description: The type of the token issued  (as per RFC 6749; always "bearer")
      expires_in:
        type: integer
        description: |
          The lifetime in seconds of the access token.  For example, the value 3600 denotes that the access token will
          expire in one hour from the time the response was generated (as per RFC 6749)
