#%RAML 1.0 DataType
#  OAuth2ErrorResponse:
    type: object
    properties:
      error:
        type: string
        description: |
          A single ASCII [USASCII] error code from the following: 
          invalid_request, unauthorized_client, unsupported_grant_type  (subset of values defined in RFC 6749)
      error_description:
        type: string
        description: Human-readable ASCII [USASCII] text providing additional information  (as per RFC 6749)
