apiVersion: v1
kind: ServiceAccount
metadata:
  name: proseo-planner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proseo-planner-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["jobs", "pods"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proseo-planner-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proseo-planner-role
subjects:
- kind: ServiceAccount
  name: proseo-planner
  namespace: default
