apiVersion: v1
kind: ServiceAccount
metadata:
  name: proseo-planner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proseo-planner-role
  # namespace not applicable for ClusterRole
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proseo-planner-binding
  # namespace not applicable for ClusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proseo-planner-role
subjects:
- kind: ServiceAccount
  name: proseo-planner
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: proseo-planner-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: proseo-planner
type: kubernetes.io/service-account-token
