FROM localhost:5000/proseo-storage-mgr:0.8.1
ADD application.yml /usr/share/proseo-storage-mgr/application.yml
ADD logback.xml /usr/share/proseo-storage-mgr/logback.xml
WORKDIR /usr/share/proseo-storage-mgr/