FROM eclipse-temurin:21
LABEL Maintainer="Thomas Bassler <thomas.bassler@drbassler.de>"
ENTRYPOINT ["java", "-jar", "/usr/share/proseo-processor-mgr/proseo-processor-mgr.jar"]

#ADD target/lib /usr/share/proseo-processor-mgr/lib
ADD target/proseo-processor-mgr.jar /usr/share/proseo-processor-mgr/proseo-processor-mgr.jar