---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proseo-storage-mgr
spec:
  selector:
    matchLabels:
      name: proseo-storage-mgr
  template:
    metadata:
      labels:
        name: proseo-storage-mgr
        app: proseo
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: proseo-storage-mgr
          image: 80.158.24.86/proseo/storage-mgr:0.0.1-SNAPSHOT-rc1
          resources:
            requests:
              cpu: "0.1"
              memory: "128M"
            limits:
              cpu: "0.5"
              memory: "256M"
          ports:
          - containerPort: 29998
            name: rpc
          - containerPort: 29999
            name: data
          - containerPort: 29996
            name: web
          volumeMounts:
            - name: alluxio-cache
              mountPath: /dev/shm
            - name: alluxio-domain
              mountPath: /opt/domain

          image: alluxio/alluxio:2.0.1
          resources:
            requests:
              cpu: "0.1"
              memory: "512M"
            limits:
              cpu: "1.5"
              memory: "1G"
          command: ["/entrypoint.sh"]
          args: ["job-worker"]
          env:
          - name: ALLUXIO_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: ALLUXIO_JOB_WORKER_JAVA_OPTS
            value: " -Dalluxio.worker.hostname=$(ALLUXIO_WORKER_HOSTNAME) "
          envFrom:
          - configMapRef:
              name: alluxio-config
          ports:
          - containerPort: 30001
            name: job-rpc
          - containerPort: 30002
            name: job-data
          - containerPort: 30003
            name: job-web
          volumeMounts:
            - name: alluxio-cache
              mountPath: /dev/shm
            - name: alluxio-domain
              mountPath: /opt/domain
      restartPolicy: Always
      volumes:
        - name: alluxio-cache
          hostPath:
            path: /mnt/alluxio
            type: DirectoryOrCreate
        - name: alluxio-domain
          hostPath:
            path: /tmp/domain
            type: DirectoryOrCreate
