---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storage-mgr
spec:
  selector:
    matchLabels:
      name: storage-mgr
  # From Kubernetes 1.17 onwards
  topologyKeys:
    - "kubernetes.io/hostname"
  template:
    metadata:
      labels:
        name: storage-mgr
        app: storage-mgr
    spec:
      imagePullSecrets:
      - name: proseo-regcred
      volumes:
      - name: mnt
        hostPath:
          path: /mnt
      containers:
        - name: proseo-storage-mgr
          image: proseo-registry.eoc.dlr.de/proseo-storage-mgr:0.1.0-SNAPSHOT-integration-rc1-403d5d1
          resources:
            requests:
              cpu: "1.0"
              memory: "512M"
            limits:
              cpu: "1.5"
              memory: "1G"
          ports:
          - name: mgr-pod-port
            containerPort: 8080
          volumeMounts:
          - name: mnt
            mountPath: /mnt
      restartPolicy: Always
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
---
kind: Service
apiVersion: v1
metadata:
  name: storage-mgr-service
  namespace: default
spec:
  type: NodePort
  ports:
  - name: service
    port: 3000
    nodePort: 30001
    targetPort: mgr-pod-port
    protocol: TCP
  selector:
    name: storage-mgr
