FROM openjdk:11
MAINTAINER Thomas Bassler <thomas.bassler@drbassler.de>
ENTRYPOINT ["java", "-jar", "/usr/share/proseo-archive-mgr/proseo-archive-mgr.jar"]

ADD target/proseo-archive-mgr.jar /usr/share/proseo-archive-mgr/proseo-archive-mgr.jar