<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<restMockResponse>
    <body>[]</body>
    <contentEncodings/>
    <headerQueries/>
    <httpHeaders/>
    <httpStatusCode>200</httpStatusCode>
    <id>hIK8PZ</id>
    <jsonPathExpressions/>
    <methodId>YSJRbz</methodId>
    <name>Empty list</name>
    <parameterQueries/>
    <status>ENABLED</status>
    <usingExpressions>false</usingExpressions>
    <xpathExpressions/>
</restMockResponse>
