<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<restMockResponse>
    <body></body>
    <contentEncodings/>
    <headerQueries/>
    <httpHeaders/>
    <httpStatusCode>204</httpStatusCode>
    <id>p32S6q</id>
    <jsonPathExpressions/>
    <methodId>xOyrAw</methodId>
    <name>No content</name>
    <parameterQueries/>
    <status>ENABLED</status>
    <usingExpressions>false</usingExpressions>
    <xpathExpressions/>
</restMockResponse>
