#%RAML 1.0 DataType
#  RestPoint:
    type: object
    properties:
      lat:
        type: number
        format: double
        description: The latitude in double format
      lon:
        type: number
        format: double
        description: The longitude in double format