---
- name: Install clamav
  yum:
    name: clamav
    state: latest

- name: Install daily cronjob
  template:
    src: clamscan-cron.j2
    dest: /etc/cron.daily/clamscan
    owner: root
    group: root
    mode: 0755

- name: Configure logrotate for clamscan
  copy:
    src: clamscan-logrotate
    dest: /etc/logrotate.d/clamscan
    owner: root
    group: root
    mode: 0644
