---
- name: Install yum-cron
  yum:
    name: yum-cron
    state: latest

- name: Enable YUM security updates
  lineinfile:
    path: /etc/yum/yum-cron.conf
    regexp: "^update_cmd *=.*"
    line: "update_cmd = security"
    create: yes
    state: present

- name: Enable various YUM cron settings
  lineinfile:
    path: /etc/yum/yum-cron.conf
    regexp: "^{{ item }} *=.*"
    line: "{{ item }} = yes"
    create: yes
    state: present
  loop:
  - update_messages
  - download_updates
  - apply_updates

- name: Enable yum-cron
  service:
    name: yum-cron
    state: started
    enabled: true

