#%RAML 1.0
title: prosEO EDIP Monitor REST Services
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: /proseo/order-gen/{version}
mediaType: application/json

securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for
                 basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password"
                       credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.

types:
  RestTrigger: !include ../../../../../model/src/main/resources/raml/types/trigger.raml


resourceTypes:
  standard:
    get?:
      responses:
        403:
          description: A cross-mission data access was attempted.
          headers:
            Warning: !include types/error.raml
        404:
          description: The requested resource was not found.
          headers:
            Warning: !include types/error.raml
    put?:
      responses:
        400:
          description: The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        403:
          description: A cross-mission data access was attempted.          
          headers:
            Warning: !include types/error.raml
        404:
          description: The requested resource was not found.
          headers:
            Warning: !include types/error.raml
    post?:
      responses:
        400:
          description: The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        403:
          description: A cross-mission data access was attempted.          
          headers:
            Warning: !include types/error.raml  
    patch?:
      responses:
        400:
          description: The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        403:
          description: A cross-mission data access was attempted.
          headers:
            Warning: !include types/error.raml
        404:
          description: The requested resource was not found                     
          headers:
            Warning: !include types/error.raml
        409:
          description: A concurrent modification was attempted.
          headers:
            Warning: !include types/error.raml
    delete?:
      responses:
        304:
          description: The resource could not be deleted.
          headers:
            Warning: !include types/error.raml
        403:
          description: A cross-mission data access was attempted.          
          headers:
            Warning: !include types/error.raml
        404:
          description: The requested resource to delete was not found.
          headers:
            Warning: !include types/error.raml
              
/triggers:
  type: standard
  get:
    description: |
      List of all triggers filtered by mission, name, type
    displayName: getTriggers
    queryParameters:
      mission?: 
        description: the mission code
        type: string
      name?: 
        description: the unique name
        type: string
      type?: 
        description: the trigger type
        type: string
    responses:
      200:
        body:
          application/json:
            type: RestTrigger[]
            example: !include ../../../../../model/src/main/resources/raml/examples/trigger-list.json
  post:
    description: |
      Create a trigger from the given JSON object
    displayName: createTrigger
    body:
      application/json:
        type: RestTrigger
        example: !include ../../../../../model/src/main/resources/raml/examples/trigger.json
    responses:
      201:
        body:
          application/json:
            type: RestTrigger
            example: !include ../../../../../model/src/main/resources/raml/examples/trigger.json
  patch:
    description: |
      Update a trigger from the given JSON object
    displayName: updateTrigger
    body:
      application/json:
        type: RestTrigger
        example: !include ../../../../../model/src/main/resources/raml/examples/trigger.json
    responses:
      201:
        body:
          application/json:
            type: RestTrigger
            example: !include ../../../../../model/src/main/resources/raml/examples/trigger.json
  delete:
    description: |
      Delete all triggers filtered by mission, name, type
    displayName: deleteTrigger
    queryParameters:
      mission: 
        description: the mission code
        type: string
      name: 
        description: the unique name
        type: string
      type: 
        description: the trigger type
        type: string
    responses:
      204:
            