
logging:
    level:
        root: INFO
        de.dlr.proseo: TRACE
management:
    endpoints.web.exposure.include: "health"
proseo:
    geotools:
        # source shape files
        shapefiles:
            -
                type: SHP
                path: ./docker/GSHHS_c_L1.shp
                shapeType: continents
            -
                type: SHP
                path: ./docker/GSHHS_c_L5.shp
                shapeType: continents
            -
                type: SHP
                path: ./docker/GSHHS_c_L5.shp
                shapeType: antarctica
            -
                type: SHP
                path: ./docker/EW_SLC_area_NE-Canada.shp
                shapeType: ne-canada
            -
                type: SHP
                path: ./docker/EW_SLC_Svalbard-polygon.shp
                shapeType: svalbard
            