#%RAML 1.0
title: prosEO Production Planner REST Services API
version: v0.1
protocols: [ HTTP, HTTPS ] 
baseUri: /proseo/planner/{version}
mediaType: application/json

types:
  RestJob: !include ../../../../../model/src/main/resources/raml/types/job.raml
  RestJobStep: !include ../../../../../model/src/main/resources/raml/types/jobstep.raml
  RestOrbit: !include ../../../../../model/src/main/resources/raml/types/orbit.raml
  RestParameter: !include ../../../../../model/src/main/resources/raml/types/parameter.raml
  RestProcessingFacility: !include ../../../../../model/src/main/resources/raml/types/processingfacility.raml
  PlannerPod: !include ../../../../../interfaces/src/main/resources/raml/types/planner-pod.raml

resourceTypes:
  standard:
    get?:
      responses:
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        404:
          description: |
            The requested resource was not found                     
          headers:
            Warning: !include types/error.raml
    put?:
      responses:          
        404:
          description: |
            The requested resource on which the modification is being attempted was not found              
          headers:
            Warning: !include types/error.raml
    delete?:
      responses:          
        404:
          description: | 
            The requested resource to delete was not found 
          headers:
            Warning: !include types/error.raml

/jobs:
  type: standard
  get:
    description: Get production planner jobs by state
    queryParameters:
      state?: string
    responses:
      200:
        body:
          application/json:
            type: RestJob[]
            example: !include ../../../../../model/src/main/resources/raml/examples/job-list.json
  /{name}:
    get:
      description: Get production planner job
      responses:
        200:
          body:
            application/json:
              type: RestJob
              example: !include ../../../../../model/src/main/resources/raml/examples/job.json
    post:
      description: Create production planner job
      responses:
        200:
          body:
            application/json:
              type: RestJob
              example: !include ../../../../../model/src/main/resources/raml/examples/job.json
    delete:
      description: Delete production planner job
      responses:
        200:
          body:
            application/json:
              type: RestJob
              example: !include ../../../../../model/src/main/resources/raml/examples/job.json

/jobsteps:
  type: standard
  get:
    description: Get production planner jobsteps
    queryParameters:
      status?:
        type: string
        enum: [ INITIAL, WAITING_INPUT, READY, RUNNING, COMPLETED, FAILED, NONE ]
    responses:
      200:
        body:
          application/json:
            type: RestJobStep[]
            example: !include ../../../../../model/src/main/resources/raml/examples/jobstep-list.json
  /{name}:
    get:
      description: Get production planner jobstep
      responses:
        200:
          body:
            application/json:
              type: RestJobStep
              example: !include ../../../../../model/src/main/resources/raml/examples/jobstep.json
    post:
      description: Create production planner jobstep
      responses:
        200:
          body:
            application/json:
              type: RestJobStep
              example: !include ../../../../../model/src/main/resources/raml/examples/jobstep.json
    delete:
      description: Delete production planner jobstep
      responses:
        200:
          body:
            application/json:
              type: RestJobStep
              example: !include ../../../../../model/src/main/resources/raml/examples/jobstep.json

/processingfacilities:
  type: standard
  get:
    description: Update and get running and connected processing facilities
    responses:
      200:
        body:
          application/json:
            type: RestProcessingFacility[]
            example: !include ../../../../../model/src/main/resources/raml/examples/processingfacility-list.json
  /{name}:
    get:
      description: Get production planner processingfacilitiy by name 
      responses:
        200:
          body:
            application/json:
              type: RestProcessingFacility
              example: !include ../../../../../model/src/main/resources/raml/examples/processingfacility.json
    /pod:
      /{podname}:
        get:
          description: Get jobstep/pod for test purpose
          responses:
            200:
              body:
                application/json:
                  type: PlannerPod
        post:
          description: Create jobstep/pod for test purpose
          queryParameters:
            stdoutLogLevel?:
              type: string
              enum: [ DEBUG, INFO, PROGRESS, WARNING, ERROR ]
            stderrLogLevel?:
              type: string
              enum: [ DEBUG, INFO, PROGRESS, WARNING, ERROR ]
          responses:
            201:
              body:
                application/json:
                  type: RestJobStep
    /pods:
      get: 
        description: Get pods on processing facility
        responses:
          200:
            body:
              application/json:
                type: PlannerPod[]
      /{status}:
        get: 
          description: Get pods on processing facility
          responses:
            200:
              body:
                application/json:
                  type: PlannerPod[]
        delete:
          description: Delete pods on processing facility
          responses:
            200:
    /finish:
      /{podname}:
        patch:
          description: Pod of name has finished with state
          queryParameters:
            status: string
          responses:
            200:
              body:
                application/json:
                  type: PlannerPod
/product:
  /{productid}:
    get:
      description: Product created and available, sent by prosEO Ingestor
      responses:
        200:
        
                