#%RAML 1.0
title: prosEO Production Planner REST Services API
version: v0.1
protocols: [ HTTP, HTTPS ] 
baseUri: /proseo/planner/{version}
mediaType: application/json

types:
  PlannerJob: !include types/planner-job.raml
  PlannerJobstep: !include types/planner-jobstep.raml
  PlannerProcessingFacility: !include types/planner-processingfacility.raml
  PlannerPod: !include types/planner-pod.raml

resourceTypes:
  standard:
    get?:
      responses:          
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        404:
          description: |
            The requested resource was not found                     
          headers:
            Warning: !include types/error.raml
    put?:
      responses:          
        404:
          description: |
            The requested resource on which the modification is being attempted was not found              
          headers:
            Warning: !include types/error.raml
    delete?:
      responses:          
        404:
          description: | 
            The requested resource to delete was not found 
          headers:
            Warning: !include types/error.raml

/jobs:
  type: standard
  get:
    description: Get production planner jobs by state
    queryParameters:
      state?: string
    responses:
      200:
        body:
          application/json:
            type: PlannerJob[]
            example: !include examples/planner-job-list.json
  /{name}:
    get:
      description: Get production planner job
      responses:
        200:
          body:
            application/json:
              type: PlannerJob
              example: !include examples/planner-job.json
    post:
      description: Create production planner job
      responses:
        200:
          body:
            application/json:
              type: PlannerJob
              example: !include examples/planner-job.json
    delete:
      description: Delete production planner job
      responses:
        200:
          body:
            application/json:
              type: PlannerJob
              example: !include examples/planner-job.json

/jobsteps:
  type: standard
  get:
    description: Get production planner jobsteps
    responses:
      200:
        body:
          application/json:
            type: PlannerJobstep[]
            example: !include examples/planner-jobstep-list.json
  /{name}:
    get:
      description: Get production planner jobstep
      responses:
        200:
          body:
            application/json:
              type: PlannerJobstep
              example: !include examples/planner-jobstep.json
    post:
      description: Create production planner jobstep
      responses:
        200:
          body:
            application/json:
              type: PlannerJobstep
              example: !include examples/planner-jobstep.json
    delete:
      description: Delete production planner jobstep
      responses:
        200:
          body:
            application/json:
              type: PlannerJobstep
              example: !include examples/planner-jobstep.json

/processingfacilities:
  type: standard
  get:
    description: Get attached processing facilities
    responses:
      200:
        body:
          application/json:
            type: PlannerProcessingFacility[]
            example: !include examples/planner-processingfacility-list.json
  /{name}:
    get:
      description: Get production planner processingfacilitiy by name 
      responses:
        200:
          body:
            application/json:
              type: PlannerProcessingFacility
              example: !include examples/planner-processingfacility.json
    /pod:
      /{podname}:
        get:
          description: Get jobstep/pod for test purpose
          responses:
            200:
              body:
                application/json:
                  type: PlannerJobstep
        post:
          description: Create jobstep/pod for test purpose
          responses:
            200:
              body:
                application/json:
                  type: PlannerJobstep
    /pods:
      get: 
        description: Get pods on processing facility
        responses:
          200:
            body:
              application/json:
                type: PlannerPod[]
      /{status}:
        get: 
          description: Get pods on processing facility
          responses:
            200:
              body:
                application/json:
                  type: PlannerPod[]
        delete:
          description: Delete pods on processing facility
          responses:
            200:
    /finish:
      /{podname}:
        patch:
          description: Pod of name has finished with state
          queryParameters:
            status: string
          responses:
            200:
              body:
                application/json:
                  type: PlannerPod
/product:
  /{productid}:
    patch:
      description: Product created and available, sent by prosEO Ingestor
      responses:
        200:
        
                