FROM openjdk:11
MAINTAINER Thomas Bassler <thomas.bassler@drbassler.de>
ENTRYPOINT ["java", "-jar", "/usr/share/proseo-ui-cli/proseo-ui-cli.jar"]

#ADD target/lib /usr/share/proseo-ui-cli/lib
ADD target/proseo-ui-cli.jar /usr/share/proseo-ui-cli/proseo-ui-cli.jar