#%RAML 1.0 DataType
#  RestStorage:
    type: RestProduct
    description: Variant of the RestProduct type with a reference to the data file location
    properties:
      sourceStorageType:
        type: string
        description: The type of the storage to ingest the data from
        pattern: ^(S3|ALLUXIO|POSIX|OTHER)$
      mountPoint:
        type: string
        description: The S3/POSIX/ALLUXIO mount point of the storage system to ingest from
      filePath:
        type: string
        description: The S3/POSIX/ALLUXIO path to the product files (relative to mountPoint)
      productFileName:
        type: string
        description: File name of the main product file
      auxFileNames?:
        type: string[]
        description: Names of auxiliary files being part of the product
      fileSize:
        type: integer
        format: long
        description: The size of the primary product file in bytes
      checksum:
        type: string
        description: Checksum value for the primary product file (computed by MD5 algorithm)
      checksumTime:
        type: string
        description: Checksum generation time in orbit format (YYYY-MM-DDThh:mm:ss.SSSSSS)
        pattern: ^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d.\d{6}$
