#%RAML 1.0 DataType
#  PlannerPod:
    type: object
    properties:
      id: string
      name: string
      starttime: string
      completiontime: string
      succeded: string
      type: string
      status: string
      log: string