#%RAML 1.0 DataType
#  RestStorage:
    type: object
    properties:
      id:
        pattern: ^proseo-[a-z0-9-]{10,50}+$
      storageType:
        type: string
        description: The type of the storage
        pattern: ^(S3|ALLUXIO|POSIX|OTHER)$
      description?: string
