docker stop proseo_proseo-gui_1
docker stop proseo_proseo-api-prip_1
docker stop proseo_proseo-order-mgr_1
docker stop proseo_proseo-processor-mgr_1
docker stop proseo_proseo-prodplanner_1
docker stop proseo_proseo-ingestor_1
docker stop proseo_proseo-productclass-mgr_1
docker stop proseo_proseo-facility-mgr_1
docker stop proseo_proseo-user-mgr_1
