FROM openjdk:11
MAINTAINER Thomas Bassler <thomas.bassler@drbassler.de>
ENTRYPOINT ["java", "-jar", "/usr/share/api/odip/proseo-api-odip.jar"]

ADD target/proseo-api-odip.jar /usr/share/api/odip/proseo-api-odip.jar