FROM eclipse-temurin:21
LABEL org.opencontainers.image.authors="Thomas Bassler <thomas.bassler@drbassler.de>"
ENTRYPOINT ["java", "-jar", "/usr/share/api/odip/proseo-api-odip.jar"]

ADD target/proseo-api-odip.jar /usr/share/api/odip/proseo-api-odip.jar