FROM localhost:5000/proseo-processor-mgr:0.8.1
ADD application.yml /usr/share/proseo-processor-mgr/application.yml
ADD logback.xml /usr/share/proseo-processor-mgr/logback.xml
WORKDIR /usr/share/proseo-processor-mgr/