---
# Prepare network settings
- name: Set hostname
  hostname:
    name: loghost
    
- name: Check existence of default route
  shell: route
  register: route_response
  
- name: Remove default route
  shell: route del default
  when: route_response.stdout.find('default') != -1
  
- name: Set default route
  shell: route add default gw {{ groups['nat_gateway'][0] }}

- name: Set DNS resolution
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: nameserver 8.8.8.8
    insertbefore: BOF
  
- name: disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  