apiVersion: 1

datasources:
  - name: prosEO-db
    uid: proseo
    type: postgres
    access: proxy
    url: "{{ (groups['dbhost'][0] | default(groups['brain'][0])) }}:5432"
    database: proseo
    user: grafana
    secureJsonData:
      password: "{{ grafana_password }}"
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    isDefault: true
    editable: true
