FROM java
MAINTAINER Thomas Bassler <thomas.bassler@drbassler.de>
ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/ingestor/ingestor.jar"]

#ADD target/lib /usr/share/ingestor/lib
ADD target/ingestor.jar /usr/share/ingestor/ingestor.jar