FROM openjdk:11
MAINTAINER Thomas Bassler <thomas.bassler@drbassler.de>
ENTRYPOINT ["java", "-jar", "/usr/share/ingestor/proseo-ingestor.jar"]

#ADD target/lib /usr/share/ingestor/lib
ADD target/proseo-ingestor.jar /usr/share/ingestor/proseo-ingestor.jar