---
# Prepare startup of InfluxDB, Grafana and Telegraf

- name: Prepare logging directories
  file:
    path: "/opt/proseo/log/{{ item }}"
    state: directory
    mode: 0755
  loop:
  - telegraf
  - influxdb/data
  - influxdb/config
  
- name: Create working directory for Grafana
  file:
    path: "/opt/proseo/log/grafana"
    state: directory
    mode: 0775

- name: Copy Telegraf configuration file
  copy:
    src: telegraf.conf
    dest: /opt/proseo/log/telegraf/telegraf.conf
    mode: 0644
  
- name: Copy Docker compose file for InfluxDB, Grafana and Telegraf
  copy:
    src: docker-compose.yml
    dest: /opt/proseo
    mode: 0644