{
 "title": "Products per Hour",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "var_mission", "label": "Missions", "query": "select code from mission" },
   {
    "name": "var_production_type",
    "label": "Production Types",
    "query": "Systematic Production : systematic_production, On-Demand Default : on-demand default, On-Demand Non-Default : on-demand non-default"
   },
   {
    "name": "var_production_type_short",
    "label": "Short",
    "query": "create or replace function get_short_type(long_type varchar(255))\nreturns varchar as\n$$\ndeclare short_type varchar(255);\n \nbegin\n\tshort_type := ''; \n\t\n\tif position('systematic_production' in long_type) > 0 then\n\t\tshort_type := short_type || '&var-var_production_type=SYSTEMATIC';\n\tend if;\n\t \n\tif position('on-demand default' in long_type) > 0 then\n\t\tshort_type := short_type || '&var-var_production_type=ON_DEMAND_DEFAULT';\n\t end if;\n\t \n\t if position('on-demand non-default' in long_type) > 0 then\n\t\tshort_type := short_type || '&var-var_production_type=ON_DEMAND_NON_DEFAULT';\n\t end if;\n  \t\n   return short_type;\nend;\n$$\nlanguage plpgsql;\n\nselect get_short_type('${var_production_type:csv}'); "
   }
  ]
 },
 "panels": [
  {
   "title": "Production latency min, max, avg ($var_production_type)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "\r\n\r\nfrom(bucket: \"production_hour\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"product\" and r[\"_field\"] =~ /type|production_latency_min/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.type == \"${var_types}\")\r\n  |> rename(columns: {production_latency_min: \"min  \"})",
     "rawSql": "SELECT\r\n  datetime at TIME zone 'UTC' AS \"time\",\r\n  min(production_latency_min) AS \"min\"\r\nFROM mon_product_production_hour this\r\nINNER JOIN mission ON mission.id = this.mission_id\r\nWHERE  \r\n  production_type IN (${var_production_type}) AND\r\n  mission.code IN (${var_mission}) AND \r\n  $__timeFilter(datetime at TIME zone 'UTC') \r\nGROUP BY datetime\r\nORDER BY datetime\r\n\r\n"
    },
    {
     "query": "from(bucket: \"production_hour\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"product\" and r[\"_field\"] =~ /type|production_latency_max/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.type == \"${var_types}\")\r\n  |> rename(columns: {production_latency_max: \"max  \"})",
     "rawSql": "SELECT\r\n  datetime at TIME zone 'UTC' AS \"time\",\r\n  max(production_latency_max) AS \"max\"\r\nFROM mon_product_production_hour this\r\nINNER JOIN mission ON mission.id = this.mission_id\r\nWHERE  \r\n  production_type IN (${var_production_type}) AND\r\n  mission.code IN (${var_mission}) AND \r\n  $__timeFilter(datetime at TIME zone 'UTC') \r\nGROUP BY datetime\r\nORDER BY datetime"
    },
    {
     "query": "from(bucket: \"production_hour\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"product\" and r[\"_field\"] =~ /type|production_latency_avg/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.type == \"${var_types}\")\r\n  |> rename(columns: {production_latency_avg: \"avg  \"})",
     "rawSql": "SELECT\r\n  datetime at TIME zone 'UTC' AS \"time\",\r\n  avg(production_latency_avg) AS \"avg\"\r\nFROM mon_product_production_hour this \r\nINNER JOIN mission ON mission.id = this.mission_id\r\nWHERE  \r\n  production_type IN (${var_production_type}) AND\r\n  mission.code IN (${var_mission}) AND \r\n  $__timeFilter(datetime at TIME zone 'UTC') \r\nGROUP BY datetime\r\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Total latency min, max, avg ($var_production_type)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"production_hour\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"product\" and r[\"_field\"] =~ /type|total_latency_min/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.type == \"${var_types}\")\r\n  |> rename(columns: {total_latency_min: \"min  \"})",
     "rawSql": "SELECT\r\n  datetime at TIME zone 'UTC' AS \"time\",\r\n  min(total_latency_min) AS \"min\"\r\nFROM mon_product_production_hour this\r\nINNER JOIN mission ON mission.id = this.mission_id\r\nWHERE  \r\n  production_type IN (${var_production_type}) AND\r\n  mission.code IN (${var_mission}) AND \r\n  $__timeFilter(datetime at TIME zone 'UTC') \r\nGROUP BY datetime\r\nORDER BY datetime"
    },
    {
     "query": "from(bucket: \"production_hour\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"product\" and r[\"_field\"] =~ /type|total_latency_max/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.type == \"${var_types}\")\r\n  |> rename(columns: {total_latency_max: \"max  \"})\r\n  ",
     "rawSql": "SELECT\r\n  datetime at TIME zone 'UTC' AS \"time\",\r\n  max(total_latency_max) AS \"max\"\r\nFROM mon_product_production_hour this\r\nINNER JOIN mission ON mission.id = this.mission_id\r\nWHERE  \r\n  production_type IN (${var_production_type}) AND\r\n  mission.code IN (${var_mission}) AND \r\n  $__timeFilter(datetime at TIME zone 'UTC') \r\nGROUP BY datetime\r\nORDER BY datetime"
    },
    {
     "query": "from(bucket: \"production_hour\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"product\" and r[\"_field\"] =~ /type|total_latency_avg/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.type == \"${var_types}\")\r\n  |> rename(columns: {total_latency_avg: \"avg  \"})",
     "rawSql": "SELECT\r\n  datetime at TIME zone 'UTC' AS \"time\",\r\n  avg(total_latency_avg) AS \"avg\"\r\nFROM mon_product_production_hour this\r\nINNER JOIN mission ON mission.id = this.mission_id\r\nWHERE  \r\n  production_type IN (${var_production_type}) AND\r\n  mission.code IN (${var_mission}) AND \r\n  $__timeFilter(datetime at TIME zone 'UTC') \r\nGROUP BY datetime\r\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Count ($var_production_type)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"production_hour\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"product\" and r[\"_field\"] =~ /type|count/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.type == \"${var_types}\")\r\n  ",
     "rawSql": "SELECT\n  datetime at TIME zone 'UTC' AS \"time\",\n  sum(count) AS \"count\"\nFROM mon_product_production_hour this\nINNER JOIN mission ON mission.id = this.mission_id\nWHERE  \n  production_type IN (${var_production_type}) AND\n  mission.code IN (${var_mission}) AND \n  $__timeFilter(datetime at TIME zone 'UTC') \nGROUP BY datetime\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Size ($var_production_type)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"production_hour\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"product\" and r[\"_field\"] =~ /type|size/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.type == \"${var_types}\")",
     "rawSql": "SELECT\n  datetime at TIME zone 'UTC' AS \"time\",\n  sum(file_size) AS file_size\nFROM mon_product_production_hour this\nINNER JOIN mission ON mission.id = this.mission_id\nWHERE  \n  production_type IN (${var_production_type}) AND\n  mission.code IN (${var_mission}) AND \n  $__timeFilter(datetime at TIME zone 'UTC') \nGROUP BY datetime\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Products per Hour ($var_production_type)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "FinalOutput = [\"Mission\", \"Date\", \"Hour\", \"Type\", \"Count\", \"Size\", \"production_latency_min\", \r\n  \"production_latency_max\", \"production_latency_avg\", \"total_latency_min\", \"total_latency_max\", \"total_latency_avg\"]\r\n\r\nRawSeries = from(bucket: \"production_hour\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"product\" and r._field =~ /mission|date|hour|type|count|size|production_latency_min|production_latency_max|production_latency_avg|total_latency_min|total_latency_max|total_latency_avg/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n//  |> filter(fn: (r) => r.type == \"${var_types}\")\r\n\r\n\r\n NamedSeries = RawSeries\r\n  |> map(fn: (r) => ({\"Mission\":r.mission, \"Date\":r.date, \"Hour\":r.hour, \"Type\":r.type, \"Count\":r.count, \"Size\":r.size, \r\n        \"production_latency_min\":r.production_latency_min, \"production_latency_max\":r.production_latency_max, \"production_latency_avg\":r.production_latency_avg, \r\n        \"total_latency_min\":r.total_latency_min, \"total_latency_max\":r.total_latency_max, \"total_latency_avg\":r.total_latency_avg}))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()",
     "rawSql": "SELECT\n  mission.code AS \"Mission\",\n  substring(cast((datetime at TIME zone 'UTC') as varchar(100)),1, 14)  AS \"Datetime\",\n  \"count\" AS \"Count\",  \n  file_size AS \"File Size\",\n  \n  CASE\n    WHEN production_type = 'systematic_production' THEN 'Systematic Production'\n    WHEN production_type = 'on-demand default' THEN 'On-Demand Default'\n    WHEN production_type = 'on-demand non-default' THEN 'On-Demand Non-Default'\n    ELSE production_type\n  END \n  AS \"Production Type\",\n  \n  production_latency_min AS \"Production Latency Min\", \n  production_latency_max AS \"Production Latency Max\", \n  production_latency_avg AS \"Production Latency Avg\", \n  total_latency_min AS \"Total Latency Min\", \n  total_latency_max AS \"Total Latency Max\", \n  total_latency_avg AS \"Total Latency Avg\" \nFROM mon_product_production_hour this\nINNER JOIN mission ON mission.id = this.mission_id\nWHERE  \n  production_type IN (${var_production_type}) AND\n  mission.code IN (${var_mission}) AND \n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  }
 ]
}