FROM openjdk:11
MAINTAINER Thomas Bassler <thomas.bassler@drbassler.de>
ENTRYPOINT ["java", "-jar", "/usr/share/api/aip-client/proseo-aip-client.jar"]

ADD target/proseo-aip-client.jar /usr/share/api/aip-client/proseo-aip-client.jar