FROM eclipse-temurin:21
LABEL org.opencontainers.image.authors="Thomas Bassler <thomas.bassler@drbassler.de>"
ENTRYPOINT ["java", "-jar", "/usr/share/api/aip-client/proseo-aip-client.jar"]

ADD target/proseo-aip-client.jar /usr/share/api/aip-client/proseo-aip-client.jar