FROM openjdk:8-jre-alpine
ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/sample-processor/proseo-sample-processor.jar"]

#ADD target/lib /usr/share/sample-processor/lib
ADD target/proseo-sample-processor.jar /usr/share/sample-processor/proseo-sample-processor.jar