---
- name: Determine network CIDR
  set_fact:
    network_cidr: "{{ ansible_default_ipv4.network }}/{{ (ansible_default_ipv4.address + '/' + ansible_default_ipv4.netmask) | ipaddr('prefix') }}"

- name: Create exports file
  blockinfile:
    dest: /etc/exports
    create: yes
    block: |
      /exports {{ network_cidr }}(rw,sync)

- name: Enable NFS
  service:
    name: nfs
    state: started
    enabled: yes
