#%RAML 1.0 DataType
#  CscProduct:
    type: object
    properties:
      Id:
        type: string
        description: Universally unique product identifier
        pattern: ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$
      Name:
        type: string
        description: Data file name
      ContentType:
        type: string
        description: The MIME type of the product (typically application/octet-stream)
      ContentLength:
        type: integer
        format: long
        description: Actual size in bytes of the downloadable file
      CreationDate:
        type: string
        description: Publication date and time of the data file (time at which the file becomes visible to the user) in UTC
        pattern: ^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d.\d{3}Z$
      EvictionDate:
        type: string
        description: Date when the data file will be removed from the rolling archive in UTC
        pattern: ^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d.\d{3}Z$
      Checksums:
        type: CscChecksum[]
        description: Represents the known checksums for the product's physical date, providing a unique value for supporting
                     download integrity check. At least MD5 checksum is mandatory.
                     It is noted that checksums are computed for the actual downloaded product file, i.e. the package used for dissemination
      ContentDate:
        type: CscTimeRange
        description: The sensing range period. Start and end times in UTC
      ProductionType:
        type: CscProductionType
        description: The type of production process applied
      Attributes?:
        type: CscAttribute[]
        description: The variable attributes of the product (as requested by the $expand option)