all:
  hosts:
    bastion-control:
      ansible_host: 85.215.220.164
      ansible_user: root
      ip: 85.215.220.164
    master:
      ansible_host: 10.9.012.15
      ip: 10.9.012.15
    worker1:
      ansible_host: 10.9.012.16
      ip: 10.9.012.16
    worker2:
      ansible_host: 10.9.012.17
      ip: 10.9.012.17
    worker3:
      ansible_host: 10.9.012.18
      ip: 10.9.012.18
    worker4:
      ansible_host: 10.9.012.19
      ip: 10.9.012.19
    worker5:
      ansible_host: 10.9.012.20
      ip: 10.9.012.20
    worker6:
      ansible_host: 10.9.012.21
      ip: 10.9.012.21
    worker7:
      ansible_host: 10.9.012.22
      ip: 10.9.012.22
    worker8:
      ansible_host: 10.9.012.23
      ip: 10.9.012.23
    worker9:
      ansible_host: 10.9.012.24
      ip: 10.9.012.24
    worker10:
      ansible_host: 10.9.012.25
      ip: 10.9.012.25
    worker11:
      ansible_host: 10.9.012.26
      ip: 10.9.012.26
    worker12:
      ansible_host: 10.9.012.27
      ip: 10.9.012.27
    worker13:
      ansible_host: 10.9.012.28
      ip: 10.9.012.28
    worker14:
      ansible_host: 10.9.012.29
      ip: 10.9.012.29
    worker15:
      ansible_host: 10.9.012.30
      ip: 10.9.012.30
    worker16:
      ansible_host: 10.9.012.31
      ip: 10.9.012.31
    worker17:
      ansible_host: 10.9.012.32
      ip: 10.9.012.32
    worker18:
      ansible_host: 10.9.012.33
      ip: 10.9.012.33
    worker19:
      ansible_host: 10.9.012.34
      ip: 10.9.012.34
    worker20:
      ansible_host: 10.9.012.35
      ip: 10.9.012.35
    worker21:
      ansible_host: 10.9.012.36
      ip: 10.9.012.36
    worker22:
      ansible_host: 10.9.012.37
      ip: 10.9.012.37
    worker23:
      ansible_host: 10.9.012.38
      ip: 10.9.012.38
    worker24:
      ansible_host: 10.9.012.39
      ip: 10.9.012.39
    worker25:
      ansible_host: 10.9.012.40
      ip: 10.9.012.40
    worker26:
      ansible_host: 10.9.012.41
      ip: 10.9.012.41
    worker27:
      ansible_host: 10.9.012.42
      ip: 10.9.012.42
    worker28:
      ansible_host: 10.9.012.43
      ip: 10.9.012.43
    worker29:
      ansible_host: 10.9.012.44
      ip: 10.9.012.44
    worker30:
      ansible_host: 10.9.012.45
      ip: 10.9.012.45
    worker31:
      ansible_host: 10.9.012.46
      ip: 10.9.012.46
    worker32:
      ansible_host: 10.9.012.47
      ip: 10.9.012.47
    worker33:
      ansible_host: 10.9.012.48
      ip: 10.9.012.48
    worker34:
      ansible_host: 10.9.012.49
      ip: 10.9.012.49
    worker35:
      ansible_host: 10.9.012.50
      ip: 10.9.012.50
    worker36:
      ansible_host: 10.9.012.51
      ip: 10.9.012.51
    worker37:
      ansible_host: 10.9.012.52
      ip: 10.9.012.52
    worker38:
      ansible_host: 10.9.012.53
      ip: 10.9.012.53
    worker39:
      ansible_host: 10.9.012.54
      ip: 10.9.012.54
  children:
    bastion:
      hosts:
        bastion-control:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        worker1:
        worker2:
        worker3:
        worker4:
        worker5:
        worker6:
        worker7:
        worker8:
        worker9:
        worker10:
        worker11:
        worker12:
        worker13:
        worker14:
        worker15:
        worker16:
        worker17:
        worker18:
        worker19:
        worker20:
        worker21:
        worker22:
        worker23:
        worker24:
        worker25:
        worker26:
        worker27:
        worker28:
        worker29:
        worker30:
        worker31:
        worker32:
        worker33:
        worker34:
        worker35:
        worker36:
        worker37:
        worker38:
        worker39:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
