all:
  hosts:
    bastion-control:
      ansible_host: 85.215.220.164
      ansible_user: root
      ip: 85.215.220.164
    master:
      ansible_host: 10.8.212.15
      ip: 10.8.212.15
    worker1:
      ansible_host: 10.8.212.16
      ip: 10.8.212.16
    worker2:
      ansible_host: 10.8.212.17
      ip: 10.8.212.17
    worker3:
      ansible_host: 10.8.212.18
      ip: 10.8.212.18
    worker4:
      ansible_host: 10.8.212.19
      ip: 10.8.212.19
    worker5:
      ansible_host: 10.8.212.20
      ip: 10.8.212.20
    worker6:
      ansible_host: 10.8.212.21
      ip: 10.8.212.21
    worker7:
      ansible_host: 10.8.212.22
      ip: 10.8.212.22
    worker8:
      ansible_host: 10.8.212.23
      ip: 10.8.212.23
    worker9:
      ansible_host: 10.8.212.24
      ip: 10.8.212.24
    worker10:
      ansible_host: 10.8.212.25
      ip: 10.8.212.25
  children:
    bastion:
      hosts:
        bastion-control:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        worker1:
        worker2:
        worker3:
        worker4:
        worker5:
        worker6:
        worker7:
        worker8:
        worker9:
        worker10:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
