FROM eclipse-temurin:21
MAINTAINER Thomas Bassler <thomas.bassler@drbassler.de>
ENTRYPOINT ["java", "-jar", "/usr/share/planner/proseo-planner.jar"]

#ADD target/lib /usr/share/planner/lib
ADD target/proseo-planner.jar /usr/share/planner/proseo-planner.jar