FROM localhost:5000/proseo-productclass-mgr:0.8.1
ADD application.yml /usr/share/proseo-productclass-mgr/application.yml
ADD logback.xml /usr/share/proseo-productclass-mgr/logback.xml
WORKDIR /usr/share/proseo-productclass-mgr/