FROM openjdk:11
MAINTAINER Thomas Bassler <thomas.bassler@drbassler.de>
ENTRYPOINT ["java", "-jar", "/usr/share/proseo-ui-gui/proseo-ui-gui.jar"]

#ADD target/lib /usr/share/proseo-ui-gui/lib
ADD target/proseo-ui-gui.jar /usr/share/proseo-ui-gui/proseo-ui-gui.jar