proseo:
    user: NONE
    password: NONE
    ingestor:
        url: http://proseo-ingestor:8080/proseo/ingestor/v0.1
    productionPlanner:
        url: http://proseo-prodplanner:8080/proseo/planner/v0.1
        # Variables to control max cycles and wait time (in milliseconds) to check file size of fetched input files
        filecheckwaittime: 1000
        filecheckmaxcycles: 50
    orderManager:
        url: http://proseo-order-mgr:8080/proseo/order-mgr/v0.1
    processorManager:
        url: http://proseo-processor-mgr:8080/proseo/processor-mgr/v0.1
    productClassManager:
        url: http://proseo-productclass-mgr:8080/proseo/productclass-mgr/v0.1
    userManager:
        url: http://proseo-user-mgr:8080/proseo/user-mgr/v0.1
    facilityManager:
        url: http://proseo-facility-mgr:8080/proseo/facility-mgr/v0.1
    gui:
        timeout: 240000
        
    # Connection timeout in ms
    http.timeout: 10000
