#%RAML 1.0
title: prosEO EDIP Monitor REST Services
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: /proseo/edip-monitor/{version}/{edipid}
mediaType: application/json


types:
  RestInterfaceStatus: !include ../../../../../../interfaces/src/main/resources/raml/types/interfaceStatus.raml

/status:
  uriParameters:
    edipid:
      description: EDIP Monitor identifier
  get:
    description: |
      Get the interface status for the given EDIP Monitor
     
      @param edipid      the EDIP Monitor identifier
      @param httpHeaders the HTTP request headers (injected)
      @return HTTP status "OK" and the Json representation of the interface status information, or HTTP status "FORBIDDEN" and an
              error message, if an invalid EDIP Monitor identifier was passed
    responses:
      200:
        body:
          application/json:
            type: RestInterfaceStatus
            example: !include ../../../../../../interfaces/src/main/resources/raml/examples/interfaceStatus.json
