#%RAML 1.0
title: prosEO EDIP Monitor REST Services
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: /proseo/edip-monitor/{version}/{edipid}
mediaType: application/json


types:
  RestInterfaceStatus: !include ../../../../../../interfaces/src/main/resources/raml/types/interfaceStatus.raml

/status:
  uriParameters:
    edipid:
      description: EDIP Monitor identifier
  get:
    description: Get status info for this EDIP Monitor
    responses:
      200:
        body:
          application/json:
            type: RestInterfaceStatus
            example: !include ../../../../../../interfaces/src/main/resources/raml/examples/interfaceStatus.json
