spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: update
        open-in-view: false
        properties.hibernate.jdbc.time_zone: UTC
    datasource:
        url: jdbc:postgresql://proseo-db:5432/proseo
        username: postgres
        password: sequel09Master
logging:
    level:
        root: INFO
        org.springframework.web.servlet: DEBUG
        de.dlr.proseo: TRACE
        org.apache.olingo: DEBUG
proseo:
    userManager.url: http://localhost:8086/proseo/user-mgr/v0.1
    ingestor.url: http://localhost:8081/proseo/ingestor/v0.1
    processorManager.url: http://localhost:8084/proseo/processor-mgr/v0.1
    facilityManager:
        url: http://localhost:8087/proseo/facility-mgr/v0.1
        user: pripapi
        password: pripapi
