FROM eclipse-temurin:21
LABEL org.opencontainers.image.authors="Thomas Bassler <thomas.bassler@drbassler.de>"
ENTRYPOINT ["java", "-jar", "/usr/share/api/prip/proseo-api-prip.jar"]

ADD target/proseo-api-prip.jar /usr/share/api/prip/proseo-api-prip.jar