FROM openjdk:11
MAINTAINER Thomas Bassler <thomas.bassler@drbassler.de>
ENTRYPOINT ["java", "-jar", "/usr/share/api/prip/proseo-api-prip.jar"]

ADD target/proseo-api-prip.jar /usr/share/api/prip/proseo-api-prip.jar