#%RAML 1.0
title: prosEO Processor Manager REST Services API
version: v0.1
protocols: [ HTTPS ] 
baseUri: /proseo/processor-mgr/{version}
mediaType: application/json

securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for
                 basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password"
                       credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.

types:
  Parameter: !include ../../../../../model/src/main/resources/raml/types/parameter.raml
  Processor: !include ../../../../../model/src/main/resources/raml/types/processor.raml
  ProcessorClass: !include ../../../../../model/src/main/resources/raml/types/processorclass.raml
  Task: !include ../../../../../model/src/main/resources/raml/types/task.raml
  Configuration: !include ../../../../../model/src/main/resources/raml/types/configuration.raml
  ConfiguredProcessor: !include ../../../../../model/src/main/resources/raml/types/configuredprocessor.raml

resourceTypes:
  standard:
    get?:
      responses:          
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        404:
          description: |
            The requested resource was not found                     
          headers:
            Warning: !include types/error.raml
    put?:
      responses:          
        404:
          description: |
            The requested resource on which the modification is being attempted was not found              
          headers:
            Warning: !include types/error.raml
    delete?:
      responses:          
        404:
          description: | 
            The requested resource to delete was not found 
          headers:
            Warning: !include types/error.raml
              
/processorclasses:
  type: standard
  get:
    description: Get processor classes by mission and name
    queryParameters:
      mission?: string
      processorName?: string
    responses:
      200:
        body:
          application/json:
            type: ProcessorClass[]
            example: !include ../../../../../model/src/main/resources/raml/examples/processorclass-list.json
  post:
    description: Create a new processor class
    body:
      application/json:
        type: ProcessorClass
        example: !include ../../../../../model/src/main/resources/raml/examples/processorclass.json
    responses:
      201:
        body:
          application/json:
            type: ProcessorClass
            example: !include ../../../../../model/src/main/resources/raml/examples/processorclass.json
  /{id}:
    uriParameters:
      id:
        type: integer
        format: long
    get:
      description: Get a processor class by ID
      responses:
        200:
          body:
            application/json:
              type: ProcessorClass
              example: !include ../../../../../model/src/main/resources/raml/examples/processorclass.json
    put:
      description: Update a processor class by ID
      body:
        application/json:
          type: ProcessorClass
          example: !include ../../../../../model/src/main/resources/raml/examples/processorclass.json
      responses:
        200:
          body:
            application/json:
              type: ProcessorClass
              example: !include ../../../../../model/src/main/resources/raml/examples/processorclass.json
    delete:
      description: Delete a processor class by ID
      responses:
        204:
              
/processors:
  type: standard
  get:
    description: Get processors by mission, name and version
    queryParameters:
      mission?: string
      processorName?: string
      processorVersion?: string
    responses:
      200:
        body:
          application/json:
            type: Processor[]
            example: !include ../../../../../model/src/main/resources/raml/examples/processor-list.json
  post:
    description: Create a new processor
    body:
      application/json:
        type: Processor
        example: !include ../../../../../model/src/main/resources/raml/examples/processor.json
    responses:
      201:
        body:
          application/json:
            type: Processor
            example: !include ../../../../../model/src/main/resources/raml/examples/processor.json
  /{id}:
    uriParameters:
      id:
        type: integer
        format: long
    get:
      description: Get a processor by ID
      responses:
        200:
          body:
            application/json:
              type: Processor
              example: !include ../../../../../model/src/main/resources/raml/examples/processor.json
    put:
      description: Update a processor class by ID
      body:
        application/json:
          type: Processor
          example: !include ../../../../../model/src/main/resources/raml/examples/processor.json
      responses:
        200:
          body:
            application/json:
              type: Processor
              example: !include ../../../../../model/src/main/resources/raml/examples/processor.json
    delete:
      description: Delete a processor class by ID
      responses:
        204:

/configurations:
  type: standard
  get:
    description: Get configurations by mission, processor name and configuration version
    queryParameters:
      mission?: string
      processorName?: string
      configurationVersion?: string
    responses:
      200:
        body:
          application/json:
            type: Configuration[]
            example: !include ../../../../../model/src/main/resources/raml/examples/configuration-list.json
  post:
    description: Create a new configuration
    body:
      application/json:
        type: Configuration
        example: !include ../../../../../model/src/main/resources/raml/examples/configuration.json
    responses:
      201:
        body:
          application/json:
            type: Configuration
            example: !include ../../../../../model/src/main/resources/raml/examples/configuration.json
  /{id}:
    uriParameters:
      id:
        type: integer
        format: long
    get:
      description: Get a configuration by ID
      responses:
        200:
          body:
            application/json:
              type: Configuration
              example: !include ../../../../../model/src/main/resources/raml/examples/configuration.json
    put:
      description: Update a configuration by ID
      body:
        application/json:
          type: Configuration
          example: !include ../../../../../model/src/main/resources/raml/examples/configuration.json
      responses:
        200:
          body:
            application/json:
              type: Configuration
              example: !include ../../../../../model/src/main/resources/raml/examples/configuration.json
    delete:
      description: Delete a configuration by ID
      responses:
        204:

/configuredprocessors:
  type: standard
  get:
    description: Get configured processors by mission, processor name, processor version and configuration version
    queryParameters:
      mission?: string
      processorName?: string
      processorVersion?: string
      configurationVersion?: string
    responses:
      200:
        body:
          application/json:
            type: ConfiguredProcessor[]
            example: !include ../../../../../model/src/main/resources/raml/examples/configuredprocessor-list.json
  post:
    description: Create a new configured processor
    body:
      application/json:
        type: ConfiguredProcessor
        example: !include ../../../../../model/src/main/resources/raml/examples/configuredprocessor.json
    responses:
      201:
        body:
          application/json:
            type: ConfiguredProcessor
            example: !include ../../../../../model/src/main/resources/raml/examples/configuredprocessor.json
  /{id}:
    uriParameters:
      id:
        type: integer
        format: long
    get:
      description: Get a configured processor by ID
      responses:
        200:
          body:
            application/json:
              type: ConfiguredProcessor
              example: !include ../../../../../model/src/main/resources/raml/examples/configuredprocessor.json
    put:
      description: Update a configured processor by ID
      body:
        application/json:
          type: ConfiguredProcessor
          example: !include ../../../../../model/src/main/resources/raml/examples/configuredprocessor.json
      responses:
        200:
          body:
            application/json:
              type: ConfiguredProcessor
              example: !include ../../../../../model/src/main/resources/raml/examples/configuredprocessor.json
    delete:
      description: Delete a configured processor by ID
      responses:
        204:
