#%RAML 1.0 DataType
#  RestAclObject:
    type: object
    properties:
      id?:
        type: integer
        format: long
        description: The persistent id of ACL object identity
      objectClass:
        type: string
        description: The class name (e. g. "de.dlr.proseo.model.Mission") of the object
      objectIdentifier:
        type: string
        description: The identifier (e. g. "S5P") of the object
      ownerSid?:
        type: integer
        format: long
        description: The persistent id of the security identity, which owns the ACL object
