#%RAML 1.0 DataType
#  RestConfigurationFile:
    type: object
    properties:
      fileVersion?:
        type: string
        description: Version string for the configuration file
      fileName:
        type: string
        description: Path name for the configuration file
