#%RAML 1.0 DataType
#  PlannerJob:
    type: object
    properties:
      id?:
        type: integer
        format: long
        description: The persistent id of this object
      version?:
        type: integer
        description: A version identifier to track updates to the object (especially to detect concurrent update attempts)
      orderIdentifier:
        type: string
        description: User-defined order identifier
      jobState:
        enum: [ INITIAL, PLANNED, RELEASED, STARTED, ON_HOLD, COMPLETED, FAILED, CLOSED ]
        description: Status of the whole job
      orbit?:
        type: RestOrbit
        description: The orbit this job relates to (if any)
      startTime?:
        type: datetime-only
        description: The start time of the time interval to process
      stopTime?:
        type: datetime-only
        description: The end time of the time interval to process
      priority:
        type: integer
        description: A processing priority (lower numbers indicate lower priority, higher numbers higher priority; the default value is 0)
      hasFailedJobSteps?:
        type: boolean
        description: Indicates whether at least one of the job steps for this job is in state FAILED
      processingFacilityName:
        type: string
        description: The name of the processing facility this job runs on
      jobSteps:
        type: RestJobStep[]
        description: The job steps for this job