#%RAML 1.0 DataType
#  Order:
    type: object
    properties:
      id?:
        type: integer
        format: long
        description: The persistent id of this object
      version?:
        type: integer
        description: A version identifier to track updates to the object (especially to detect concurrent update attempts)
      missionCode:
        type: string
        description: The mission code (e. g. S5P)
      identifier:
        type: string
        description: User-defined order identifier
      orderState:
        type: string
        description: State of the processing order; one of { INITIAL, RELEASED, PLANNED, RUNNING, COMPLETED, FAILED, CLOSED }
      executionTime?:
        type: datetime
        description: Expected execution time (optional, used for scheduling)
      startTime?:
        type: datetime
        description: The start time of the time interval to process. If a range of orbit numbers is given, this time is set to 
                     the earliest start time of the selected orbits.
      stopTime?:
        type: datetime
        description: The end time of the time interval to process. If a range of orbit numbers is given, this time is set to 
                     the latest stop time of the selected orbits.
      filterConditions:
        type: Parameter[]
        description: A set of additional conditions to apply to selected products.
      outputParameters:
        type: Parameter[]
        description: A set of parameters to set for the generated products.
      configuredProcessors:
        type: string[]
        description: List of identifiers of the configured processors
      orbits:
        type: OrbitQuery[]
        description: List of orbit ranges, identified by spacecraft code and orbit number from/to
      requestedProductClasses:
        type: string[]
        description: List of internal product types
      processingMode:
        type: string
        description: The processing mode to run the processor(s) in
      promisedProducts:
        type: PromisedProduct[]
        description: List of products provided as input to the processing order
