#%RAML 1.0 DataType
#  RestOrder:
    type: object
    properties:
      id?:
        type: integer
        format: long
        description: The persistent id of this object
      version?:
        type: integer
        description: A version identifier to track updates to the object (especially to detect concurrent update attempts)
      missionCode:
        type: string
        description: The mission code (e. g. S5P)
      identifier:
        type: string
        description: User-defined order identifier
      orderState:
        type: string
        description: State of the processing order; one of { INITIAL, RELEASED, PLANNED, RUNNING, COMPLETED, FAILED, CLOSED }
      executionTime?:
        type: datetime-only
        description: Expected execution time (optional, used for scheduling)
      startTime?:
        type: datetime-only
        description: The start time of the time interval to process. If a range of orbit numbers is given, this time is set to 
                     the earliest start time of the selected orbits.
      stopTime?:
        type: datetime-only
        description: The end time of the time interval to process. If a range of orbit numbers is given, this time is set to 
                     the latest stop time of the selected orbits.
      slicingType:
        type: string
        description: One of { "ORBIT", "CALENDAR_DAY", "TIME_SLICE" }
      sliceDuration?:
        type: integer
        description: Duration of a slice in seconds (only if slicingType == "TIME_SLICE")
      sliceOverlap:
        type: integer
        description: Overlap between adjacent slices in seconds
      filterConditions:
        type: RestParameter[]
        description: A set of additional conditions to apply to selected products.
      outputParameters:
        type: RestParameter[]
        description: A set of parameters to set for the generated products.
      configuredProcessors:
        type: string[]
        description: List of identifiers of the configured processors
      orbits:
        type: RestOrbitQuery[]
        description: List of orbit ranges, identified by spacecraft code and orbit number from/to
      requestedProductClasses:
        type: string[]
        description: List of internal product types requested as output from the order
      inputProductClasses:
        type: string[]
        description: List of internal product types given as input to the order
      outputFileClass:
        type: string
        description: The file class for the generated output products
      processingMode:
        type: string
        description: The processing mode to run the processor(s) in
