#%RAML 1.0 DataType
#  RestOrder:
    type: object
    properties:
      id?:
        type: integer
        format: long
        description: The persistent id of this object
      version?:
        type: integer
        description: A version identifier to track updates to the object (especially to detect concurrent update attempts)
      missionCode:
        type: string
        description: The mission code (e. g. S5P)
      identifier:
        type: string
        description: User-defined order identifier
      uuid?:
        type: string
        description: Universally unique order identifier
        pattern: ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$
      orderState:
        type: string
        description: State of the processing order; one of { INITIAL, APPROVED, RELEASED, PLANNED, RUNNING, SUSPENDING, COMPLETED, FAILED, CLOSED }
      executionTime?:
        type: datetime-only
        description: Expected execution time (optional, used for scheduling)
      startTime?:
        type: string
        description: The start time of the time interval to process in orbit format (YYYY-MM-DDThh:mm:ss[.SSSSSS]). If a range of
                     orbit numbers is given, this time is set to the earliest start time of the selected orbits.
        pattern: ^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d(.\d{1,6})?$
      stopTime?:
        type: string
        description: The end time of the time interval to process in orbit format (YYYY-MM-DDThh:mm:ss[.SSSSSS]). If a range of
                     orbit numbers is given, this time is set to the latest stop time of the selected orbits.
        pattern: ^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d(.\d{1,6})?$
      slicingType:
        type: string
        description: One of { "ORBIT", "CALENDAR_DAY", "CALENDAR_MONTH", "CALENDAR_YEAR", "TIME_SLICE", "NONE" }
      sliceDuration?:
        type: integer
        description: Duration of a slice in seconds (only for slicingType TIME_SLICE)
      sliceOverlap?:
        type: integer
        description: Overlap between adjacent slices in seconds (applicable for all slicingTypes except NONE, default 0)
      inputFilters?:
        type: RestInputFilter[]
        description: Filter conditions to apply to input products
      classOutputParameters?:
        type: RestClassOutputParameter[]
        description: Set of parameters to apply to a generated product of the referenced product class replacing the general output parameters
      outputParameters:
        type: RestParameter[]
        description: Parameters to set for the generated products
      configuredProcessors:
        type: string[]
        description: List of identifiers of the configured processors
      orbits:
        type: RestOrbitQuery[]
        description: List of orbit ranges, identified by spacecraft code and orbit number from/to
      requestedProductClasses:
        type: string[]
        description: List of internal product types requested as output from the order
      inputProductClasses:
        type: string[]
        description: List of internal product types given as input to the order
      outputFileClass:
        type: string
        description: The file class for the generated output products
      processingMode:
        type: string
        description: The processing mode to run the processor(s) in
      productionType?:
        type: string
        description: Production type context, in which the order is running (SYSTEMATIC, ON_DEMAND_DEFAULT, ON_DEMAND_NON_DEFAULT)
      productRetentionPeriod?:
        type: integer
        format: long
        description: Retention period for products generated by this processing order in seconds
      hasFailedJobSteps?:
        type: boolean
        description: Indicates whether at least one of the job steps for this order is in state FAILED
      jobStepStates?:
        type: string[]
        description: The different existing job step states of order
      percentCompleted?:
        type: integer
        description: Percentage of completed job steps
      percentFailed?:
        type: integer
        description: Percentage of failed job steps
      percentRunning?:
        type: integer
        description: Percentage of running job steps
