#%RAML 1.0 DataType
#  RestOrderTemplate:
    type: object
    properties:
      id?:
        type: integer
        format: long
        default: 0
        description: The persistent id of this object
      version?:
        type: integer
        default: 1
        description: A version identifier to track updates to the object (especially to detect concurrent update attempts)
      missionCode:
        type: string
        description: The mission code (e. g. S5P)
      name:
        type: string
        description: Short name of the order template
      priority?:
         type: integer
         format: int
         default: 50
         description: Priority of the ProcessingOrder (lower number means lower priority; value range 1..100 is defined for the ODIP, but other values are allowed outside On-Demand Production, including negative numbers). Default value is 50.         
      outputFileClass:
        type: string
        description: The file class for the generated output products
      processingMode:
        type: string
        description: The processing mode to run the processor(s) in
      slicingType:
        type: string
        default: NONE
        description: One of { "ORBIT", "CALENDAR_DAY", "CALENDAR_MONTH", "CALENDAR_YEAR", "TIME_SLICE", "NONE" }
      sliceDuration?:
        type: integer
        description: Duration of a slice in seconds (only for slicingType TIME_SLICE)
      sliceOverlap?:
        type: integer
        default: 0
        description: Overlap between adjacent slices in seconds (applicable for all slicingTypes except NONE, default 0)
      inputFilters?:
        type: RestInputFilter[]
        description: Filter conditions to apply to input products
      dynamicProcessingParameters?:
        type: RestParameter[]
        description: |
          Processing option settings (for on-demand processing called "WorkflowOptions" in the ICD); these options will be passed
          to the data processors in the "Dynamic Processing Parameter" section of the Job Order file
      classOutputParameters?:
        type: RestClassOutputParameter[]
        description: Set of parameters to apply to a generated product of the referenced product class replacing the general output parameters
      outputParameters:
        type: RestParameter[]
        description: Parameters to set for the generated products (may be empty)
      configuredProcessors:
        type: string[]
        description: List of identifiers of the configured processors (may be empty)
      requestedProductClasses:
        type: string[]
        description: List of internal product types requested as output from the order (at least one is required)
      inputProductClasses:
        type: string[]
        description: List of internal product types provided as input to the order (may be empty) 
      productionType?:
        type: string
        description: Production type context, in which the order is running (SYSTEMATIC, ON_DEMAND_DEFAULT, ON_DEMAND_NON_DEFAULT)
      notificationEndpoint?:
        type: RestNotificationEndpoint
        description: The endpoint to send order completion notifications to
      productRetentionPeriod?:
        type: integer
        format: long
        description: Retention period for products generated by this processing order in seconds
      autoRelease?:
        type: boolean
        default: false
        description: Flag determining whether the processing order will be released automatically
      autoClose?:
        type: boolean
        default: false
        description: Flag determining whether the order will be closed immediately after successful completion
      inputDataTimeoutPeriod?:
        type: integer
        format: long
        description: Timeout period for input data to arrive, before order is cancelled or executed with available data
      onInputDataTimeoutFail?:
        type: boolean
        default: true
        description: Flag determining whether the order will fail when the input timeout period is reached
      enabled?:
        type: boolean
        default: true
        description: Flag determining whether the order template is usable
