#%RAML 1.0 DataType
#  RestPayload:
    type: object
    properties:
      name:
        type: string
        description: The payload name (instrument short name), e. g. "TROPOMI".
      description:
        type: string
        description: The payload description