#%RAML 1.0 DataType
#  ProcessingFacility:
    type: object
    properties:
      id?:
        type: integer
        format: long
        description: The persistent id of this object
      version?:
        type: integer
        description: A version identifier to track updates to the object (especially to detect concurrent update attempts)
      name:
        type: string
        description: The facility name (unique key)
      description?:
        type: string
        description: A short description of the processing facility
      processingEngineUrl:
        type: string
        description: The URL to access this facility's processing engine (Kubernetes instance)
      storageManagerUrl:
        type: string
        description: The URL to access this facility's storage manager
