#%RAML 1.0 DataType
#  RestProcessor:
    type: object
    properties:
      id?:
        type: integer
        format: long
        description: The persistent id of this object
      version?:
        type: integer
        description: A version identifier to track updates to the object (especially to detect concurrent update attempts)
      missionCode:
        type: string
        description: The mission code (e. g. S5P)
      processorName:
        type: string
        description: The name of the processor class this processor (version) belongs to
      processorVersion:
        type: string
        description: Version identification of the processor executable (Docker image)
      isTest?:
        type: boolean
        default: false
        description: Indicates a test version of the processor (default false)
      minDiskSpace?:
        type: integer
        default: 1024
        description: Minimum disk space in MB, worst case estimate plus safety margin (default 1024)
      maxTime?:
        type: integer
        default: 0
        description: Execution time limit in seconds (default 0 means unlimited)
      sensingTimeFlag?:
        type: boolean
        default: true
        description: Indicates whether the processor uses a sensing time interval as main processing parameter (default true)
      configuredProcessors:
        type: string[]
        description: The names for the processor configurations this processor version is valid for
      tasks:
        type: RestTask[]
        description: List of tasks for this processor
      dockerImage:
        type: string
        description: The name of the docker image (without registry address)
      dockerRunParameters?:
        type: string
        description: Parameters to add to the "docker run" command
