#%RAML 1.0 DataType
#  RestProductFile:
    type: object
    properties:
      id?:
        type: integer
        format: long
        default: 0
        description: The persistent id of this object
      version?:
        type: integer
        default: 1
        description: A version identifier to track updates to the object (especially to detect concurrent update attempts)
      productId:
        type: integer
        format: long
        description: Id value of the product this product file belongs to
      processingFacilityName:
        type: string
        description: The name of the processing facility, in which this product file is stored
      productFileName:
        type: string
        description: The name of the product data file
      auxFileNames:
        type: string[]
        description: The auxiliary files for this product file
      filePath:
        type: string
        description: The path to the product files (POSIX file path, S3 bucket etc.)
      storageType:
        type: string
        description: The string representation of the type of the storage location (e. g. "S3", "POSIX")
      fileSize:
        type: integer
        format: long
        description: The size of the primary product file in bytes
      checksum:
        type: string
        description: Checksum value for the primary product file (computed by MD5 algorithm)
      checksumTime:
        type: string
        description: Checksum generation time in orbit format (YYYY-MM-DDThh:mm:ss.SSSSSS)
        pattern: ^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d.\d{6}$
      zipFileName?:
        type: string
        description: The file name of the ZIP archive containing all product and auxiliary files intended for distribution
      zipFileSize?:
        type: integer
        format: long
        description: The file size of the ZIP archive in bytes
      zipChecksum?:
        type: string
        description: The MD5 checksum for the ZIP archive
      zipChecksumTime?:
        type: string
        description: ZIP archive checksum generation time in orbit format (YYYY-MM-DDThh:mm:ss.SSSSSS)
        pattern: ^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d.\d{6}$
