#%RAML 1.0 DataType
#  RestSimpleSelectionRule:
    type: object
    properties:
      id?:
        type: integer
        format: long
        description: The persistent id of this object
      version?:
        type: integer
        description: A version identifier to track updates to the object (especially to detect concurrent update attempts)
      mode?:
        type: string
        description: Processing modes as defined for the enclosing mission
      isMandatory:
        type: boolean
        description: Indicates whether the required source product is mandatory for the production of the target product
      minimumCoverage?:
        type: integer
        format: int16
        default: 0
        description: Minimum percentage of coverage of the desired validity period for fulfilment of this rule (default 0)
      filterConditions:
        type: RestParameter[]
        description: Parameter values to filter the selected products (triple of parameter key, parameter type and parameter value);
                     checked against product parameter values by equality.
      targetProductClass:
        type: string
        description: The product class which uses the selection rule
      sourceProductClass:
        type: string
        description: The product class which is selected by this rule
      applicableConfiguredProcessors:
        type: string[]
        description: A list of identifiers for processor configurations, for which this rule is applicable
      simplePolicies:
        type: RestSimplePolicy[]
        description: The selection policies applied for selecting target products (the first applicable policy in the list holds)
      ruleString:
        type: string
        description: The rule string of this selection rule