#%RAML 1.0 DataType
#  RestSpacecraft:
    type: object
    properties:
      id?:
        type: integer
        format: long
        default: 0
        description: The persistent id of this object
      version?:
        type: integer
        default: 1
        description: A version identifier to track updates to the object (especially to detect concurrent update attempts)
      code:
        type: string
        description: The short code for the spacecraft (e. g. TDX1)
      name:
        type: string
        description: The spacecraft name (e. g. TanDEM-X)
      payloads?:
        type: RestPayload[]
        description: The payloads flying on this spacecraft
