#%RAML 1.0 DataType
#  Spacecraft:
    type: object
    properties:
      code:
        type: string
        description: The short code for the spacecraft (e. g. TDX1)
      name:
        type: string
        description: The spacecraft name (e. g. TanDEM-X)
