#%RAML 1.0 DataType
#  RestStringParameter:
    type: object
    properties:
      key:
        type: string
        description: The parameter key
      value:
        type: string
        description: The parameter value