#%RAML 1.0
title: prosEO Storage Manager REST Services
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: /proseo/storage-mgr/{version}
mediaType: application/json


types:
  RestInfo: !include ../../../../../interfaces/src/main/resources/raml/types/info.raml
  RestStorage: !include ../../../../../interfaces/src/main/resources/raml/types/storage.raml
  RestProductFS: !include ../../../../../interfaces/src/main/resources/raml/types/productFS.raml
  RestJoborder: !include ../../../../../interfaces/src/main/resources/raml/types/joborderBase64.raml


resourceTypes:
  standard:
    get?:
      responses:
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        404:
          description: |
            The requested resource was not found
          headers:
            Warning: !include types/error.raml
    put?:
      responses:
        404:
          description: |
            The requested resource on which the modification is being attempted was not found
          headers:
            Warning: !include types/error.raml
    delete?:
      responses:
        404:
          description: |
            The requested resource to delete was not found
          headers:
            Warning: !include types/error.raml
/info:
  get:
    description: get infos for this storage-manager
    responses:
      200:
        body:
          application/json:
            type: RestInfo

/products:
  get:
    description: Get product metadata, optionally filtered by storage type, product (database) ID
    queryParameters:
      storageType?:
        enum: [S3, ALLUXIO, POSIX]
      id?:
        type: integer
        format: long
    responses:
      200:
        body:
          application/json:
            type: RestProductFS[]
  post:
    description: Register products/files/dirs from unstructered storage in prosEO-storage
    body:
      application/json:
        type: RestProductFS
        example: !include ../../../../../interfaces/src/main/resources/raml/examples/productFS.json
    responses:
      201:
        body:
          application/json:
            type: RestProductFS
            example: !include ../../../../../interfaces/src/main/resources/raml/examples/productFS-reg.json
  delete:
    description: Delete/remove product by product path info from prosEO storage
    queryParameters:
      pathInfo: 
        type: string
        description: The file path as S3/ALLUXIO/POSIX string for download
    responses:
      200:
        body:
          application/json:
            type: RestProductFS
            example: !include ../../../../../interfaces/src/main/resources/raml/examples/productFS-del.json
  /download:
    get:
      description: Get the data files for the product as data stream (optionally zip-compressed, optionally range-restricted)
      queryParameters:
        pathInfo: 
          type: string
          description: The file path as S3/ALLUXIO/POSIX string for download
        fromByte?: integer
        toByte?: integer
      responses:
        200:
          body:
            application/octet-stream:

/productfiles:
  description: Methods to transfer product files between Storage Manager and processor (Base Wrapper)
  get:
    description: Retrieve file from Storage Manager into locally accessible file system
    queryParameters:
      pathInfo: 
        type: string
        description: The file path as S3/ALLUXIO/POSIX string for download
    responses:
      200:
        body:
          text/plain:
            description: The resulting file path in the local POSIX file system
  put:
    description: Push file from local POSIX file system to Storage Manager
    queryParameters:
      pathInfo: 
        type: string
        description: The file path as local POSIX path for upload
      productId:
        type: integer
        format: long
        description: The product id used to generate target file path
    responses:
      201:
        body:
          text/plain:
            description: |
              The file system type (S3/ALLUXIO/POSIX), followed by a vertical bar ('|'),
              followed by the resulting S3/ALLUXIO/POSIX file path
              
/joborders:
  post:
    description: Upload prosEO Job Order File for later use in a job
    body:
      application/json:
        type: RestJoborder
        example: !include ../../../../../interfaces/src/main/resources/raml/examples/joborderBase64.json
    responses:
      201:
        body:
          application/json:
            type: RestJoborder
            example: !include ../../../../../interfaces/src/main/resources/raml/examples/joborderBase64-response.json
  get:
    description: Download prosEO Job Order File as Base64-encoded string
    queryParameters:
      pathInfo: string
    responses:
      200:
        body:
          text/plain:
            description: The resulting Base64-encoded string
