#%RAML 1.0
title: prosEO Storage Manager REST Services API
version: v0.1
protocols: [ HTTPS ] 
baseUri: https://proseo.eoc.dlr.de/{version}/order-mgr
mediaType: application/json

securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for
                 basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password"
                       credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.

types:
  Storage: !include types/storage.raml

resourceTypes:
  standard:
    get?:
      responses:          
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        404:
          description: |
            The requested resource was not found                     
          headers:
            Warning: !include types/error.raml
    put?:
      responses:          
        404:
          description: |
            The requested resource on which the modification is being attempted was not found              
          headers:
            Warning: !include types/error.raml
    delete?:
      responses:          
        404:
          description: | 
            The requested resource to delete was not found 
          headers:
            Warning: !include types/error.raml
              
/storages:
  type: standard
  get:
    description: Get storages by id
    queryParameters:
      id?: string
    responses:
      200:
        body:
          application/json:
            type: Storage[]
            example: !include examples/storage-list.json
  post:
    description: Create a new storage
    body:
      application/json:
        type: Storage
        example: !include examples/storage.json
    responses:
      201:
        body:
          application/json:
            type: Storage
            example: !include examples/storage.json
  