#%RAML 1.0
title: prosEO Storage Manager REST Services
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: /proseo/storage-mgr/{version}
mediaType: application/json


types:
  Info: !include types/info.raml
  ProcFacility: !include types/procFacility.raml
  Storage: !include types/storage.raml
  ProductFS: !include types/productFS.raml
  Joborder: !include types/joborderBase64.raml


resourceTypes:
  standard:
    get?:
      responses:
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        404:
          description: |
            The requested resource was not found
          headers:
            Warning: !include types/error.raml
    put?:
      responses:
        404:
          description: |
            The requested resource on which the modification is being attempted was not found
          headers:
            Warning: !include types/error.raml
    delete?:
      responses:
        404:
          description: |
            The requested resource to delete was not found
          headers:
            Warning: !include types/error.raml
/info:
  get:
    description: get infos for this storage-manager
    responses:
      200:
        body:
          application/json:
            type: Info
/processingFacility:
  get:
    description: get name of processingFacility where this storage-manager resides...(1:1)
    responses:
      200:
        body:
          application/json:
            type: ProcFacility

/{procFacilityName}/storages:
  type: standard
  get:
    description: Get storages by id
    queryParameters:
      id?: string
    responses:
      200:
        body:
          application/json:
            type: Storage[]
            example: !include examples/storage-list.json
  post:
    description: Create a new storage
    body:
      application/json:
        type: Storage
        example: !include examples/storage.json
    responses:
      201:
        body:
          application/json:
            type: Storage
            example: !include examples/storage.json
  /{storageId}:
    /register:
      post:
        description: register products/files/dirs from unstructered storage in prosEO-storage
        body:
          application/json:
            type: ProductFS
            example: !include examples/productFS.json
        responses:
          201:
            body:
              application/json:
                type: ProductFS
                example: !include examples/productFS-reg.json
    /products:
      get:
        description: get product-infos by Id
        queryParameters:
          id?: string
        responses:
          200:
            body:
              application/json:
                type: ProductFS
      /{productId}:
        delete:
          description: delete/remove product having productId from prosEO storage
          responses:
            200:
              body:
                application/json:
                  type: ProductFS
                  example: !include examples/productFS-del.json

/{procFacilityName}/joborders:
    post:
      description: upload prosEO joborder file for later use in a job
      body:
        application/json:
          type: Joborder
          example: !include examples/joborderBase64.json
      responses:
        201:
          body:
            application/json:
              type: Joborder
              example: !include examples/joborderBase64-response.json
