#%RAML 1.0
title: prosEO CADIP Monitor REST Services
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: /proseo/cadip-monitor/{version}/{cadipid}
mediaType: application/json


types:
  RestInterfaceStatus: !include ../../../../../../interfaces/src/main/resources/raml/types/interfaceStatus.raml

/status:
  uriParameters:
    cadipid:
      type: string
      description: CADIP Monitor identifier
  get:
    description: |
      Get the interface status for the given CADIP Monitor
     
      @param cadipid     the CADIP Monitor identifier
      @param httpHeaders the HTTP request headers (injected)
      @return HTTP status "OK" and the Json representation of the interface status information, or HTTP status "FORBIDDEN" and an
              error message, if an invalid CADIP Monitor identifier was passed
    responses:
      200:
        body:
          application/json:
            type: RestInterfaceStatus
            example: !include ../../../../../../interfaces/src/main/resources/raml/examples/interfaceStatus.json
