---
- name: Enable TCP forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ".*AllowTcpForwarding.*"
    line: "AllowTcpForwarding yes"
    create: yes
    state: present

- name: Disable root logins
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ".*PermitRootLogin.*"
    line: "PermitRootLogin no"
    create: yes
    state: present

- name: Restartd SSHD
  service:
    name: sshd
    state: restarted
