- name: Ensure EPEL repository is present
  yum:
    name: epel-release

- name: Install rkhunter
  yum:
    name: rkhunter
    state: latest

- name: Set rkhunter notification email
  lineinfile:
    path: /etc/sysconfig/rkhunter
    regexp: "^ *MAILTO.*"
    line: "MAILTO={{ rkhunter_email|default('root@localhost') }}"
    create: yes
    state: present

- name: Disallow SSH root users
  lineinfile:
    path: /etc/rkhunter.conf
    regexp: "^ALLOW_SSH_ROOT_USER=.*"
    line: "ALLOW_SSH_ROOT_USER=no"
    create: yes
    state: present

- name: Prevent warning for missing SSH protocol entry
  lineinfile:
    path: /etc/rkhunter.conf
    regexp: "^ALLOW_SSH_PROT_V1=.*"
    line: "ALLOW_SSH_PROT_V1=2"
    create: yes
    state: present
