---
- name: Install yum-cron and postfix for notifications
  yum:
    name:
    - yum-cron
    - postfix
    state: latest

- name: Enable YUM security updates
  lineinfile:
    path: /etc/yum/yum-cron.conf
    regexp: "^update_cmd *=.*"
    line: "update_cmd = security"
    create: yes
    state: present

- name: Enable various YUM cron settings
  lineinfile:
    path: /etc/yum/yum-cron.conf
    regexp: "^{{ item }} *=.*"
    line: "{{ item }} = yes"
    create: yes
    state: present
  loop:
  - update_messages
  - download_updates
  - apply_updates

- name: Set YUM cron mail notification recipient
  lineinfile:
    path: /etc/yum/yum-cron.conf
    regexp: "^email_to *=.*"
    line: "email_to = {{ yumcron_email|default('root@localhost') }}"
    create: yes
    state: present

- name: Enable postfix
  service:
    name: postfix
    state: started
    enabled: true

- name: Enable yum-cron
  service:
    name: yum-cron
    state: started
    enabled: true

