#%RAML 1.0
title: prosEO Product Class Manager REST Services API
version: v0.1
protocols: [ HTTPS ] 
baseUri: /proseo/productclass-mgr/{version}
mediaType: application/json

securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for
                 basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password"
                       credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.

types:
  ProductClass: !include types/productclass.raml

resourceTypes:
  standard:
    get?:
      responses:          
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        404:
          description: |
            The requested resource was not found                     
          headers:
            Warning: !include types/error.raml
    put?:
      responses:          
        404:
          description: |
            The requested resource on which the modification is being attempted was not found              
          headers:
            Warning: !include types/error.raml
    delete?:
      responses:          
        404:
          description: | 
            The requested resource to delete was not found 
          headers:
            Warning: !include types/error.raml
              
/productclasses:
  type: standard
  get:
    description: Get product classes by id
    queryParameters:
      id?: string
    responses:
      200:
        body:
          application/json:
            type: ProductClass[]
            example: !include examples/productclass-list.json
  post:
    description: Create a new product class
    body:
      application/json:
        type: ProductClass
        example: !include examples/productclass.json
    responses:
      201:
        body:
          application/json:
            type: ProductClass
            example: !include examples/productclass.json
  