#%RAML 1.0
title: prosEO XBIP Monitor REST Services
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: /proseo/xbip-monitor/{version}/{xbipid}
mediaType: application/json


types:
  RestInterfaceStatus: !include ../../../../../../interfaces/src/main/resources/raml/types/interfaceStatus.raml

/status:
  uriParameters:
    xbipid:
      description: XBIP Monitor identifier
  get:
    description: |
      Get the interface status for the given XBIP Monitor
    responses:
      200:
        body:
          application/json:
            type: RestInterfaceStatus
            example: !include ../../../../../../interfaces/src/main/resources/raml/examples/interfaceStatus.json
