#%RAML 1.0
title: prosEO Ingestor REST Services API
version: v0.1
protocols: [ HTTPS ] 
baseUri: /proseo/ingestor/{version}
baseUriParameters:
  port:
    description: The port the application is running on
mediaType: application/json

securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for
                 basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password"
                       credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.

types:
  RestProduct: !include ../../../../../model/src/main/resources/raml/types/product.raml
  ProductFile: !include ../../../../../model/src/main/resources/raml/types/productfile.raml
  Parameter: !include ../../../../../model/src/main/resources/raml/types/parameter.raml
  IngestorProduct:
    type: RestProduct
    description: Variant of the RestProduct type with a reference to the data file location
    properties:
      mountPoint:
        type: string
        description: The POSIX mount point of the storage system to ingest from
      filePath:
        type: string
        description: The POSIX path to the product files
      productFileName:
        type: string
        description: File name of the main product file
      auxFileNames?:
        type: string[]
        description: Names of auxiliary files being part of the product

resourceTypes:
  standard:
    get?:
      responses:          
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        404:
          description: |
            The requested resource was not found                     
          headers:
            Warning: !include types/error.raml
    put?:
      responses:          
        404:
          description: |
            The requested resource on which the modification is being attempted was not found              
          headers:
            Warning: !include types/error.raml
    patch?:
      responses:          
        404:
          description: |
            The requested resource on which the modification is being attempted was not found              
          headers:
            Warning: !include types/error.raml
    delete?:
      responses:          
        404:
          description: | 
            The requested resource to delete was not found 
          headers:
            Warning: !include types/error.raml
              
/products:
  type: standard
  description: Methods to manage product metadata in the database
  get:
    description: List of all products by mission, product class, start time range
    displayName: getProducts
    queryParameters:
      mission?: string
      productClass?: string[]
      startTimeFrom?: datetime
      startTimeTo?: datetime
    responses:
      200:
        body:
          application/json:
            type: RestProduct[]
            example: !include ../../../../../model/src/main/resources/raml/examples/product-list.json
  post:
    description: Create a new product
    displayName: createProduct
    body:
      application/json:
        type: RestProduct
        example: !include ../../../../../model/src/main/resources/raml/examples/product.json
    responses:
      201:
        body:
          application/json:
            type: RestProduct
            example: !include ../../../../../model/src/main/resources/raml/examples/product.json
  /{id}:
    uriParameters:
      id:
        type: integer
        format: long
    get:
      description: Get a product by ID
      displayName: getProductById
      responses:
        200:
          body:
            application/json:
              type: RestProduct
              example: !include ../../../../../model/src/main/resources/raml/examples/product.json
    patch:
      description: Update a product by ID
      displayName: modifyProduct
      body:
        application/json:
          type: RestProduct
          example: !include ../../../../../model/src/main/resources/raml/examples/product.json
      responses:
        200:
          body:
            application/json:
              type: RestProduct
              example: !include ../../../../../model/src/main/resources/raml/examples/product.json
    delete:
      description: Delete a product by ID
      responses:
        204:
        
/ingest:
  type: standard
  description: Methods to manage product files in the processing facility and in the database
  /{processingFacility}:
    uriParameters:
      processingFacility:
        type: string
        description: The name of the facility to ingest the products to
    post:
      description: Ingest all given products into the storage manager of the given processing facility
      displayName: ingestProducts
      body:
        application/json:
          type: IngestorProduct[]
          example: !include examples/ingestorproduct-list.json
      responses:
        201:
          body:
            application/json:
              type: RestProduct[]
              example: !include ../../../../../model/src/main/resources/raml/examples/product-list.json
    /{productId}:
      uriParameters:
        productId:
          type: integer
          format: long
          description: The ID of the product to ingest product files for
      get:
        description: Get the product file for a product at a given processing facility
        responses:
          200:
            body:
              application/json:
                type: ProductFile
                example: !include ../../../../../model/src/main/resources/raml/examples/productfile.json
      post:
        description: Create a new product file for a product at a given processing facility
        displayName: ingestProductFile
        body:
          application/json:
            type: ProductFile
            example: !include ../../../../../model/src/main/resources/raml/examples/productfile.json
        responses:
          201:
            body:
              application/json:
                type: ProductFile
                example: !include ../../../../../model/src/main/resources/raml/examples/productfile.json
      patch:
        description: Update a product file for a product at a given processing facility
        body:
          application/json:
            type: ProductFile
            example: !include ../../../../../model/src/main/resources/raml/examples/productfile.json
        responses:
          200:
            body:
              application/json:
                type: ProductFile
                example: !include ../../../../../model/src/main/resources/raml/examples/productfile.json
      delete:
        description: Delete a product file for a product from a given processing facility
        displayName: deleteProductFile
        responses:
          204:
        