/**
 * OrderTemplate.java
 * 
 * (C) 2026 Dr. Bassler & Co. Managementberatung GmbH
 */
package de.dlr.proseo.model;

import java.time.Duration;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import de.dlr.proseo.model.enums.ProductionType;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Index;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;

/**
 * This class aims at simplifying the generation of processing orders, either for automatic generation due to 
 * an OrderTrigger firing, or for manual generation, e. g. from the GUI or CLI. The template specifies values for 
 * various attributes to be set in a ProcessingOrder.
 * 
 * @since prosEO 2.1.0
 * 
 * @author Dr. Thomas Bassler
 */
@Entity
@Table(indexes = { 
		@Index(unique = true, columnList = "mission_id,name")})
public class OrderTemplate extends OrderTemplateBase {

	/**
	 * Processing option settings (for on-demand processing called "WorkflowOptions" in the ICD); these options will be passed
	 * to the data processors in the "Dynamic Processing Parameter" section of the Job Order file.
	 */
	@ElementCollection
	private Map<String, Parameter> dynamicProcessingParameters = new HashMap<>();
	
	/** Set of requested product classes */
	@ManyToMany
	private Set<ProductClass> requestedProductClasses = new HashSet<>();
	
	/** Set of product classes provided as input data (processing job steps must not be generated) */
	@ManyToMany
	private Set<ProductClass> inputProductClasses = new HashSet<>();
	
	/** Production type context, in which the order is running */
	@Enumerated(EnumType.STRING)
	private ProductionType productionType = ProductionType.ON_DEMAND_DEFAULT;
	
	/** The endpoint to send order completion notifications to */
	private NotificationEndpoint notificationEndpoint;
	
	/** 
	 * Period between product generation time and product eviction time for all products generated by job steps of this
	 * processing order (not just those of the output product classes). If the eviction period is not set, it will be taken
	 * from the mission default value; if that is not present either, no eviction time will be computed for the products.
	 */
	private Duration productRetentionPeriod;
	
    /**
     * If set the processing order will be released automatically either immediately after planning or 
     * when its executionTime is reached, whichever comes later.
     */
	@Column(columnDefinition = "boolean not null default false")
    private boolean autoRelease = false;
    
    /**
     * If set, the order will be closed immediately after successful completion.
     */
    @Column(columnDefinition = "boolean not null default false")
    private boolean autoClose = false;
    
    /**
     * If set, the order will fail or will automatically be started regardless of input data availability,
     * when the given duration after the release time has elapsed. 
     * Start or failure are determined by the setting of onInputDataTimeoutFail.
     */
    private Duration inputDataTimeoutPeriod;
    
    /**
     * If true (the default setting) and inputDataTimeoutPeriod is set, the order will fail when the timeout period 
     * after the release time is expired and the input data is not complete; if false, the order will then be started 
     * regardless of the availability of its input data.
     */
    @Column(columnDefinition = "boolean not null default true")
    private boolean onInputDataTimeoutFail = true;

	/** The processor configurations for processing the products */
	@ManyToMany
	private Set<ConfiguredProcessor> requestedConfiguredProcessors = new HashSet<>();
	
	/**
	 * @return the productionType
	 */
	public ProductionType getProductionType() {
		return productionType;
	}

	/**
	 * @param productionType the productionType to set
	 */
	public void setProductionType(ProductionType productionType) {
		this.productionType = productionType;
	}

	/**
	 * Gets the dynamic processing parameters to be set for the Job Orders in this order
	 * 
	 * @return the dynamicProcessingParameters
	 */
	public Map<String, Parameter> getDynamicProcessingParameters() {
		return dynamicProcessingParameters;
	}

	/**
	 * Sets the dynamic processing parameters to be set for the Job Orders in this order
	 * 
	 * @param dynamicProcessingParameters the dynamicProcessingParameters to set
	 */
	public void setDynamicProcessingParameters(Map<String, Parameter> dynamicProcessingParameters) {
		this.dynamicProcessingParameters = dynamicProcessingParameters;
	}

	/**
	 * Gets the requested product classes
	 * 
	 * @return the requestedProductClasses
	 */
	public Set<ProductClass> getRequestedProductClasses() {
		return requestedProductClasses;
	}

	/**
	 * Sets the requested product classes
	 * 
	 * @param requestedProductClasses the requestedProductClasses to set
	 */
	public void setRequestedProductClasses(Set<ProductClass> requestedProductClasses) {
		this.requestedProductClasses = requestedProductClasses;
	}

	/**
	 * Gets the input product classes provided to the order
	 * 
	 * @return the input product classes
	 */
	public Set<ProductClass> getInputProductClasses() {
		return inputProductClasses;
	}

	/**
	 * Sets the input product classes provided to the order
	 * 
	 * @param inputProductClasses the input product classes to set
	 */
	public void setInputProductClasses(Set<ProductClass> inputProductClasses) {
		this.inputProductClasses = inputProductClasses;
	}

	/**
	 * @return the notificationEndpoint
	 */
	public NotificationEndpoint getNotificationEndpoint() {
		return notificationEndpoint;
	}

	/**
	 * @param notificationEndpoint the notificationEndpoint to set
	 */
	public void setNotificationEndpoint(NotificationEndpoint notificationEndpoint) {
		this.notificationEndpoint = notificationEndpoint;
	}

	/**
	 * Gets the retention period for products generated by this processing order
	 * 
	 * @return the product retention period
	 */
	public Duration getProductRetentionPeriod() {
		return productRetentionPeriod;
	}

	/**
	 * Sets the retention period for products generated by this processing order
	 * 
	 * @param productRetentionPeriod the product retention period to set
	 */
	public void setProductRetentionPeriod(Duration productRetentionPeriod) {
		this.productRetentionPeriod = productRetentionPeriod;
	}

	/**
	 * Indicates whether a processing order reaching state PLANNED will automatically be released
	 * 
	 * @return true, if the order will be released automatically, false otherwise
	 */
	public boolean isAutoRelease() {
		return autoRelease;
	}

	/**
	 * Sets a flag indicating whether a processing order reaching state PLANNED shall automatically be released
	 * 
	 * @param autoRelease set to true, if the order shall be released automatically, and to false otherwise
	 */
	public void setAutoRelease(boolean autoRelease) {
		this.autoRelease = autoRelease;
	}

	/**
	 * Indicates whether a processing order reaching state COMPLETED will automatically be closed
	 * 
	 * @return true, if the order will be closed automatically, false otherwise
	 */
	public boolean isAutoClose() {
		return autoClose;
	}

	/**
	 * Sets a flag indicating whether a processing order reaching state COMPLETED shall automatically be closed
	 * 
	 * @param autoClose set to true, if the order shall be closed automatically, and to false otherwise
	 */
	public void setAutoClose(boolean autoClose) {
		this.autoClose = autoClose;
	}

	/**
	 * Gets the period of time, after which the order will fail or will automatically be started regardless of input data 
	 * availability
	 * 
	 * @return the input data timeout period
	 */
	public Duration getInputDataTimeoutPeriod() {
		return inputDataTimeoutPeriod;
	}

	/**
	 * Sets the period of time, after which the order shall fail or shall automatically be started regardless of input data 
	 * availability
	 * 
	 * @param inputDataTimeoutPeriod the input data timeout period to set
	 */
	public void setInputDataTimeoutPeriod(Duration inputDataTimeoutPeriod) {
		this.inputDataTimeoutPeriod = inputDataTimeoutPeriod;
	}

	/**
	 * Indicates whether the order will fail after the input data timeout period has elapsed
	 * 
	 * @return true, if the order will fail after timeout, false, if it will be processed with incomplete input data
	 */
	public boolean isOnInputDataTimeoutFail() {
		return onInputDataTimeoutFail;
	}

	/**
	 * Sets a flag indicating whether the order will fail after the input data timeout period has elapsed
	 * 
	 * @param onInputDataTimeoutFail set to true, if the order shall fail after timeout, and to false, if it shall be processed 
	 * with incomplete input data
	 */
	public void setOnInputDataTimeoutFail(boolean onInputDataTimeoutFail) {
		this.onInputDataTimeoutFail = onInputDataTimeoutFail;
	}

	/**
	 * Gets the requested configured processors
	 * 
	 * @return the requestedConfiguredProcessors
	 */
	public Set<ConfiguredProcessor> getRequestedConfiguredProcessors() {
		return requestedConfiguredProcessors;
	}

	/**
	 * Sets the requested configured processors
	 * 
	 * @param requestedConfiguredProcessors the requestedConfiguredProcessors to set
	 */
	public void setRequestedConfiguredProcessors(Set<ConfiguredProcessor> requestedConfiguredProcessors) {
		this.requestedConfiguredProcessors = requestedConfiguredProcessors;
	}

	@Override
	public String toString() {
		return "OrderTemplate [ " + super.toString() + ", dynamicProcessingParameters=" + dynamicProcessingParameters 
				+ ", requestedProductClasses=" + requestedProductClasses + ", inputProductClasses=" + inputProductClasses 
				+ ", productionType=" + productionType + ", notificationEndpoint=" + notificationEndpoint 
				+ ", productRetentionPeriod=" + productRetentionPeriod
				+ ", autoRelease=" + autoRelease + ", autoClose=" + autoClose + ", inputDataTimeoutPeriod=" + inputDataTimeoutPeriod
				+ ", onInputDataTimeoutFail=" + onInputDataTimeoutFail 
				+ ", requestedConfiguredProcessors=" + requestedConfiguredProcessors + "]";
	}

}
