logging:
    file: /proseo/log/proseo-cadip-monitor.log
    level:
        root: INFO
        de.dlr.proseo: TRACE
 #       org.apache.http: DEBUG
 #       org.springframework.web.client: DEBUG
proseo:
    # The Ingestor URI (protocol, host name, port, context; no terminating slash)
    ingestor.url: http://localhost:8081/proseo/ingestor/v1 

    # CADIP Monitor configuration
    cadip:
        # CADIP Monitor identifier (must be unique for all CADIP monitors on the same host)
        id: PTM-CADIP
        # The base URI of the CADIP (protocol, host name, port; no terminating slash)
        baseuri: http://localhost:8080
        # The CADIP context, if any ("service root", any URI component(s) before "odata"; no starting or terminating slash)
        context: proseo/api/prip
        
        # The product types to select
        producttypes: "AUX_IERSC,AUX_IERSB"
        
        # Flag indicating whether token-based authentication shall be used (default false)
        usetoken: true
        # The URI for requesting a bearer token (full URL)
        tokenuri: http://localhost:8080/proseo/api/prip/token
        # The CADIP username
        user: myuser
        # The CADIP password
        password: mypassword
        # Credentials for OpenID-based token requests (optional)
        client:
            # The CADIP client ID
            id: my-client-id
            # The CADIP client secret (mandatory if client ID is set)
            secret: mysecret
            # Send client ID and secret in body?
            sendinbody: false
            
        # Interval between pickup point checks in milliseconds (e. g. every min)
        check.interval: 60000
        # Interval between individual chunk retrievals in milliseconds (e. g. every 10 s)
        chunk.interval: 10000
        
        # Handling of history file
        history:
            # Path to the file for storing transfer history (on a persistent volume)
            file: /Path/to/transfer/history/file
            # Interval to truncate transfer history file in milliseconds (e. g. daily)
            truncate.interval: 86400000
            # Period to retain transfer history entries for, in milliseconds (e. g. one week)
            retention: 604800000
            
        # Handling of parallel threads
        thread:
            # Maximum number of parallel transfer threads (default 1 = no parallel threads)
            # max: 1
            # Interval in millliseconds to check for completed transfers (default 500 ms)
            # wait: 500
            # Maximum number of wait cycles for transfer completion checks (default 3600)
            # cycles: 3600
            
        # Minimum size in bytes of a file to be used for performance measurements (e. g. 20 MiB = 20 * 1024 * 1024 Bytes)
        performance.minsize: 20971520
            
        # The path to the target AUX file directory (for ingestion)
        directory: /Path/to/transfer/directory
