#%RAML 1.0
title: prosEO Monitor REST Services API
version: v0.1
protocols: [ HTTP, HTTPS ] 
baseUri: /proseo/notification/{version}
mediaType: application/json

types:
  RestMessage: !include ../../../../../interfaces/src/main/resources/raml/types/message.raml

/notify:
  post:
    description: |
      Process and send the REST message
    displayName: notifyx
    body:
      application/json:
        type: RestMessage
        example: !include ../../../../../interfaces/src/main/resources/raml/examples/message.json
    responses:
      201:
        body:
          text/plain:
      400:
        description: The request sent to the server contains data which is not as expected e.g. invalid location URI
        headers:
          Warning: !include types/error.raml
      403:
        description: A cross-mission data access was attempted.
        headers:
          Warning: !include types/error.raml
      500:
        description: An internal service error occured.
        headers:
          Warning: !include types/error.raml