spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate.ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/proseo?serverTimezone=Europe/Berlin
        username: root
        password: sequel09Master
    packagesToScan: de.dlr.proseo.model
logging:
    level:
        root: INFO
        de:
            dlr:
                proseo: TRACE
proseo:
    productionPlanner:
        url: https://localhost:8091/proseo/planner/v0.1
        user: none
        password: none
    storageManager:
        user: none
        password: none
