spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: update
        open-in-view: false
        properties.hibernate.jdbc.time_zone: UTC
    datasource:
        url: jdbc:postgresql://proseo-db:5432/proseo
        username: <db_user>
        password: <db_pwd>
logging:
    level:
        root: INFO
        de.dlr.proseo: TRACE
proseo:
    log:
        # Host and port for InfluxDB monitoring
        host: http://localhost:8086
        # Authentication token for InfluxDB
        token: TheInfluxDBToken
        # InfluxDB organization to use
        org: proseo
        # InfluxDB bucket to use
        bucket: production
    productionPlanner:
        url: http://proseo-prodplanner:8080/proseo/planner/v0.1
        # Connection timeout in ms
        timeout: 10000
        # Variables to control max cycles and wait time (in milliseconds) to check file size of fetched input files
        filecheckwaittime: 1000
        filecheckmaxcycles: 50
    storageManager:
        # Connection timeout in ms
        timeout: 30000
        # Shared secred for download token
        secret: MyVeryLongSecretMustBeAtLeast32Bytes
        # Validity period for download token
        validity: 60000
