#%RAML 1.0 DataType
#  Headers:
#    Warning:
       description: An error code and a plain text error message
       pattern: ^\d{3} proseo-storage-mgr \(.\d+\) .+$
       example: 199 proseo-storage-mgr (E5505) The path is null
