#%RAML 1.0 DataType
# JoborderBase64:
    type: object
    properties:
      jobOrderStringBase64?:
        type: string
        maxLength: 100000
      uploaded?: boolean
      fsType?:
        enum: [S3,ALLUXIO,POSIX]
      pathInfo?: string
      message?: string
