#%RAML 1.0
title: prosEO On-Demand Production Interface Delivery Point (ODIP) REST Services API
version: v0.1
protocols: [ HTTPS ] 
baseUri: /proseo/odip/odata/{version}
mediaType: application/octet-stream

securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for
                 basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password"
                       credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.

types:
  CscChecksum: !include types/checksum.raml
  CscTimeRange: !include types/timerange.raml
  CscAttribute: !include types/attribute.raml
  CscProductionType: !include types/productiontype.raml
  CscProduct: !include types/product.raml

/Products('{Id}')/$value:
  description: Methods for downloading products according to ESA's On-Demand Production Interface Delivery Point (ODIP) API
  displayName: DownloadController
  uriParameters:
    Id:
      type: string
      description: Universally unique product identifier
      pattern: ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$
  get:
    description: Download the product with the given identifier
    responses:
      200:
        description: The request was successfully completed
        body:
          application/octet-stream:
      400:
        description: |
          The request sent to the server contains data which is not as expected e.g. invalid URI parameters
        headers:
          Warning: !include types/error.raml
      401:
        description: |
          The requesting user is unauthorised to download the product
      404:
        description: |
          The requested resource was not found (i. e. the product does not exist or is not available any more)
        headers:
          Warning: !include types/error.raml
