---
- name: Install dnf-automatic
  ansible.builtin.dnf:
    name: dnf-automatic
    state: present

- name: Configure dnf-automatic
  ansible.builtin.template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart dnf-automatic timer

- name: Enable dnf automatic install timer
  ansible.builtin.systemd:
    name: dnf-automatic-install.timer
    enabled: true
    state: started