---
# The externally mounted file system for product ingestion (simulated)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: proseo-ingest-share
  labels:
    name: proseo-ingest-share
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain 
  hostPath:
    path: /opt/prosEO/data/transfer
    type: Directory

---
# The common storage area for Storage Manager and Processing Engine
apiVersion: v1
kind: PersistentVolume
metadata:
  name: proseo-nfs-share
  labels:
    name: proseo-nfs-share
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain 
  hostPath:
    path: /opt/prosEO/data/proseodata
    type: Directory
