#%RAML 1.0
title: prosEO Product Archive Manager REST Services API
version: v0.1
protocols: [ HTTPS ] 
baseUri: /proseo/archive-mgr/{version}
mediaType: application/json

securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for
                 basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password"
                       credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.

types:
  RestProductArchive: !include ../../../../../../model/src/main/resources/raml/types/productarchive.raml

resourceTypes:
  standard:
    get?:
      responses:          
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. invalid location URI
          headers:
            Warning: !include types/error.raml
        404:
          description: |
            The requested resource was not found                     
          headers:
            Warning: !include types/error.raml
    patch?:
      responses:          
        404:
          description: |
            The requested resource on which the modification is being attempted was not found              
          headers:
            Warning: !include types/error.raml
    delete?:
      responses:          
        404:
          description: | 
            The requested resource to delete was not found 
          headers:
            Warning: !include types/error.raml
              
/archives:
  type: standard
  get:
    description: |
      List of product archives with search criteria
    displayName: getArchives
    queryParameters:
      name?: 
        type: string
        description: the product archive name
      archiveType?: 
        type: string
        description: the product archive type   
      recordFrom?: 
        type: integer
        format: int32
        description: first record of filtered and ordered result to return
      recordTo?:
        type: integer
        format: int32
        description: last record of filtered and ordered result to return
    responses:
      200:
        body:
          application/json:
            type: RestProductArchive[]
            example: !include ../../../../../../model/src/main/resources/raml/examples/productarchive-list.json
  post:
    description: |
      Create a product archive from the given Json object
    displayName: createArchive
    body:
      application/json:
        type: RestProductArchive
        example: !include ../../../../../../model/src/main/resources/raml/examples/productarchive.json
    responses:
      201:
        body:
          application/json:
            type: RestProductArchive
            example: !include ../../../../../../model/src/main/resources/raml/examples/productarchive.json
            
  /count:
    get:
      description: |
        Count the product archive matching the specified name, archive type.
      displayName: countArchives
      queryParameters:
        name?: 
          type: string
          description: the product archive name
        archiveType?: 
          type: string
          description: the product archive type
      responses:
        200:
          body:
            text/plain:
  /{id}:
    uriParameters:
      id:
        type: integer
        format: long
    get:
      description: |
        Find the product archive with the given ID
      displayName: getArchiveById
      responses:
        200:
          body:
            application/json:
              type: RestProductArchive
              example: !include ../../../../../../model/src/main/resources/raml/examples/productarchive.json
    patch:
      description: |
        Update the product archive with the given ID with the attribute values of the given Json object.
      displayName: modifyArchive
      body:
        application/json:
          type: RestProductArchive
          example: !include ../../../../../../model/src/main/resources/raml/examples/productarchive.json
      responses:
        200:
          body:
            application/json:
              type: RestProductArchive
              example: !include ../../../../../../model/src/main/resources/raml/examples/productarchive.json
        304:
          body:
            application/json:
              type: RestProductArchive
              example: !include ../../../../../../model/src/main/resources/raml/examples/productarchive.json
    delete:
      description: |
        Delete a product archive by ID
      displayName: deleteArchiveById
      responses:
        204: