---
- name: Ensure Docker repository is available
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    
- name: Install Docker
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    
- name: Start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Download Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
