logging:
    file: /proseo/log/proseo-storage-mgr.log
    level:
        root: INFO
        de.dlr.proseo: TRACE
 #       org.apache.http: DEBUG
 #       org.springframework.web.client: DEBUG
proseo:
    global:
      storageIdPrefix: proseo
      storageManagerVersion2: true
      # Default mount point for files to upload
      sourcePath: default

    s3:
      s3AccessKey: short_access_key
      s3SecretAccessKey: short_secret_key
      s3EndPoint: http://192.168.20.191:9000
      s3Region: eu-central-1
      s3MaxNumberOfBuckets: 50
      s3DefaultBucket: proseo-data-001
      s3DefaultEndPoint: false

    posix:
      # Mount point for backend storage (must be different from cachePath)
      backendPath: /proseo/data/backend
      # Mount point for file cache
      cachePath: /proseo/data/cache
      
    joborder:
      bucket: internal
      prefix: joborders
      
    storageManager:
      # Default type for backend storage
      defaultStorageType: S3
      
      # Control checks on input files
      filecheck:
        # Wait time between checks
        waittime: 500
        # Maximum number of checks
        maxcycles: 600
        # Maximum request attempts
        maxRequestAttempts: 3 
        
      # Shared secret for download token
      secret: MyVeryLongSecretMustBeAtLeast32Bytes
      
      # File cache control
      cache:
        # Recommended minimum cache usage for efficient operation (percentage of file system size)
        expectedUsage: 75
        # Maximum cache usage (percentage of file system size)
        maximumUsage: 85
