logging:
    level:
        root: INFO
        de.dlr.proseo: TRACE
 #       org.apache.http: DEBUG
 #       org.springframework.web.client: DEBUG
proseo:
    global:
      storageIdPrefix: proseo

    s3:
      s3AccessKey: short_access_key
      s3SecretAccessKey: short_secret_key
      s3EndPoint: http://192.168.20.191:9000
      s3Region: eu-de
      s3MaxNumberOfBuckets: 50
      s3DefaultBucket: proseo-data-001

    alluxio:
      alluxioUnderFsS3Bucket: internal
      alluxioUnderFsS3BucketPrefix: underfs

      # Alluxio configuration values currently not in use       
#      alluxioUnderFsDefaultPrefix: proseo-alluxio-cache
#      alluxioUnderFsS3BucketEndPoint: http://192.168.20.191:9000
#      alluxioUnderFsMaxPrefixes: 500

    posix:
      mountPoint: /proseo/data
      workerMountPoint: /proseo/data
    joborder:
      bucket: internal
      prefix: joborders
    storageManager:
        defaultStorageType: S3
        # Variables to control max cycles and wait time (in milliseconds) to check file size of fetched input files
        filecheckwaittime: 1000
        filecheckmaxcycles: 50
          
    # Alluxio configuration values currently not in use       
#    mountpoints:
#     #ALLUXIO-properties are only used for answering GET-requests on endpoint /info
#      alluxio:
#        k8sNode:
#          alluxioCache: /mnt/alluxio
#          alluxioFuse: /alluxio-fuse
          
    # Connection timeout in ms
    http.timeout: 10000
        