proseo:
    global:
      storageIdPrefix: proseo
    procFacility:
      name: devel
      url: http://localhost:9887/k8s-api-endpoint
      descr: local env :-)
    s3:
      s3AccessKey: short_access_key
      s3SecretAccessKey: short_secret_key
      s3EndPoint: http://192.168.20.159:9000
      s3Region: eu-de
      s3MaxNumberOfBuckets: 50
      s3DefaultBucket: proseo-data-001
    alluxio:
      alluxioUnderFsS3Bucket: internal
      alluxioUnderFsS3BucketPrefix: underfs
      alluxioUnderFsDefaultPrefix: proseo-alluxio-cache
      alluxioUnderFsS3BucketEndPoint: http://192.168.20.159:9000
      alluxioUnderFsMaxPrefixes: 500
    posix:
      mountPoint: /mnt/proseodata
      workerMountPoint: /mnt/localproseodata
    joborder:
      bucket: internal
      prefix: joborders
    storageManager:
        user: PTM-wrapper
        password: ingest&plan
        defaultStorageType: S3
    mountpoints:
     #ALLUXIO-properties are only used for answering GET-requests on endpoint /info
      alluxio:
        k8sNode:
          alluxioCache: /mnt/alluxio
          alluxioFuse: /alluxio-fuse
      #Required for handling a mounted storage-appliance, available at every k8s-Node as POSIX-mountpoint
      unregisteredProducts:
        k8sNode:
          unregisteredProducts: ""
          
        