# package_all_notests.yml
#
# (C) 2024 Dr. Bassler & Co. Managementberatung GmbH
#
# Creates java packages without test execution
# 
# @author Denys Chaykovskiy
#

name: Package all no tests

on:
  push:
    branches: [ "dev-denys" ]
  pull_request:
    branches: [ "dev-denys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '15.x'
    - name: Install dependencies
      run: npm install
    
    - name: Install raml2html
      run: npm i -g raml2html
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Package all no tests
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
