#%RAML 1.0 DataType
#  Headers:
#    Warning:
       description: An error code and a plain text error message
       pattern: ^\d{3} proseo-processor-mgr \(.\d+\) .+$
       example: 199 proseo-processor-mgr (E4503) Configuration data not set
