---
# Grab kubectl config from first master
- hosts: kube-master[0]
  become: true
  roles:
  - fetch_kubectl

# Configure bastion
- hosts: bastion
  become: true
  vars:
    kubectl_users:
    - linux
    - root
    firewall_services:
    - http
    - https
    - nfs
    kubectl_proxy_port: 8001
  roles:
  - configure_sshd  # Already done in bastion-preinstall, but this allows updates
  - install_kubectl
  - install_packages
  - configure_nfs
  - configure_kube_api_proxy
  - configure_nginx_proxy
