{
 "title": "Cockpit",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "var_service",
    "label": "Services",
    "query": "SELECT mon_service.name\nFROM mon_service_state_operation\nINNER JOIN mon_service on mon_service_state_operation.mon_service_id = mon_service.id\nWHERE $__timeFilter(mon_service_state_operation.datetime at TIME zone 'UTC')\nGROUP BY 1; "
   },
   {
    "name": "var_processing_order",
    "label": "Orders",
    "query": "SELECT processing_order.identifier\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE $__timeFilter(processing_order_mon_order_progress.datetime  at TIME zone 'UTC')\nGROUP BY 1; \n\n\n"
   },
   {
    "name": "var_mission_id",
    "label": "Mission",
    "query": "create or replace function get_missions()\nreturns varchar as\n$$\n\ndeclare\n    sql varchar;\n\nbegin\n\n   sql = '123&456';\n   return sql;\n\nend;\n$$\nlanguage plpgsql;\n\nselect get_missions();"
   },
   {
    "name": "var_production_type",
    "label": "Production Types",
    "query": "Systematic Production : systematic_production, On-Demand Default : on-demand default, On-Demand Non-Default : on-demand non-default"
   },
   {
    "name": "var_production_type_short",
    "label": "Short",
    "query": "create or replace function get_short_type(long_type varchar(255))\nreturns varchar as\n$$\ndeclare short_type varchar(255);\n \nbegin\n\tshort_type := ''; \n\t\n\tif position('systematic_production' in long_type) > 0 then\n\t\tshort_type := short_type || '&var-var_production_type=SYSTEMATIC';\n\tend if;\n\t \n\tif position('on-demand default' in long_type) > 0 then\n\t\tshort_type := short_type || '&var-var_production_type=ON_DEMAND_DEFAULT';\n\t end if;\n\t \n\t if position('on-demand non-default' in long_type) > 0 then\n\t\tshort_type := short_type || '&var-var_production_type=ON_DEMAND_NON_DEFAULT';\n\t end if;\n  \t\n   return short_type;\nend;\n$$\nlanguage plpgsql;\n\nselect get_short_type('${var_production_type:csv}'); "
   }
  ]
 },
 "panels": [
  {
   "title": "Menu (scroll down)",
   "type": "text",
   "gridPos": { "h": 21, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<b>Services</b><br><br>\n\n<a href=\"/d/uid_services/services?orgId=1&from=now-1h&to=now&var-var_service=${var_service}\">Last hour</a><br>\n<a href=\"/d/uid_services_per_day/services-per-day?orgId=1&from=now-31d&to=now&var-var_service=${var_service}\">Last 31 days (aggregated)</a><br>\n<a href=\"/d/uid_services_per_month/services-per-month?orgId=1&from=now-24M&to=now&var-var_service=${var_service}\">Last 24 month (aggregated)</a><br><br>\n\n<b>Processing Orders</b><br><br>\n\n<a href=\"/d/uid_processing_orders/processing-orders?orgId=1&from=now-1h&to=now&var-var_processing_order=${var_processing_order}\">Last hour</a><br>\n<a href=\"/d/uid_processing_orders/processing-orders?orgId=1&from=${__from}&to=${__to}&var-var_processing_order=${var_processing_order}\">Selected time range</a><br><br>\n\n<b>Products</b><br><br>\n\n<a href=\"/d/uid_products/products?orgId=1&from=now-1h&to=now&${var_production_type_short}\">Last hour</a><br>\n<a href=\"/d/uid_products_per_hour/products-per-hour?orgId=1&from=now-24h&to=now&${var_production_type:queryparam}\">Last 24 hours (aggregated)</a><br>\n<a href=\"/d/uid_products_per_day/products-per-day?orgId=1&from=now-31d&to=now&${var_production_type:queryparam}\">Last 31 days (aggregated)</a><br>\n<a href=\"/d/uid_products_per_month/products-per-month?orgId=1&from=now-24M&to=now&${var_production_type:queryparam}\">Last 24 months (aggregated)</a><br><br>\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "${var_service} (selected)",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 13, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nINNER JOIN mon_service on mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = '${var_service}')\nWHERE  \n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "$var_service (selected)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n (SELECT\n    COUNT(*)  \n  FROM\n    mon_service_state_operation\n  WHERE\n    mon_service_id = (SELECT id FROM mon_service WHERE name='$var_service') AND\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\n\n  / (SELECT\n    COUNT(*)  \n  FROM\n    mon_service_state_operation\n  WHERE\n    mon_service_id = (SELECT id FROM mon_service WHERE name='$var_service') AND\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\n  * 100;\n"
    }
   ]
  },
  {
   "title": "${var_service} (selected)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ext_service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"extService_1\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nINNER JOIN mon_service on mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = '${var_service}')\nWHERE  \n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "${var_processing_order} (selected processing order: Failed + Completed = Finished Job Steps)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 20, "x": 4, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|failed_job_steps/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")",
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   failed_job_steps as failed\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime"
    },
    {
     "query": "from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|completed_job_steps/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")",
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   completed_job_steps as completed\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime\n"
    },
    {
     "query": "from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|finished_job_steps/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")",
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   finished_job_steps as finished\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   all_job_steps as all\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime\n"
    },
    {
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   running_job_steps as running\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime\n"
    }
   ]
  }
 ]
}