{
 "title": "Processing Orders",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "var_processing_order",
    "label": "Processing Orders",
    "query": "SELECT processing_order.identifier\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE $__timeFilter(processing_order_mon_order_progress.datetime  at TIME zone 'UTC')\nGROUP BY 1; \n\n\n"
   }
  ]
 },
 "panels": [
  {
   "title": "${var_processing_order} (selected processing order: Failed + Completed = Finished Job Steps)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|failed_job_steps/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")",
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   failed_job_steps as failed\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime"
    },
    {
     "query": "from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|completed_job_steps/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")",
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   completed_job_steps as completed\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime\n"
    },
    {
     "query": "from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|finished_job_steps/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")",
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   finished_job_steps as finished\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   all_job_steps as all\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime\n"
    },
    {
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   running_job_steps as running\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "All Job Steps (${var_processing_order})",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|all_job_steps/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")",
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   all_job_steps\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Job Steps Info (${var_processing_order})",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "FinalOutput = [\"Order\", \"Time\" \"All\", \"Completed\", \"Failed\", \"Finished\", \"Running\"]\r\n\r\nRawSeries = from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|all_job_steps|finished_job_steps|completed_job_steps|failed_job_steps|running_job_steps/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Order\":r.name, \"Time\":r._time, \"All\":r.all_job_steps, \"Completed\":r.completed_job_steps, \r\n          \"Failed\":r.failed_job_steps, \"Finished\": r.finished_job_steps, \"Running\":r.running_job_steps}))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()",
     "rawSql": "SELECT\n  processing_order.identifier AS order_identifier, \n  mon_order_state.name AS state, \n  all_job_steps AS all, \n  failed_job_steps AS failed, \n  finished_job_steps AS finished, \n  completed_job_steps AS completed, \n  running_job_steps AS running, \n  processing_order_mon_order_progress.datetime at TIME zone 'UTC' AS \"time\"\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nINNER JOIN mon_order_state on processing_order_mon_order_progress.mon_order_state_id = mon_order_state.id\nWHERE\n  $__timeFilter(processing_order_mon_order_progress.datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Failed Job Steps (${var_processing_order})",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|failed_job_steps/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")",
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   failed_job_steps\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Completed Job Steps (${var_processing_order})",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|completed_job_steps/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")",
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   completed_job_steps\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Job Steps Info (all)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "query": "FinalOutput = [\"Order\", \"Time\" \"All\", \"Completed\", \"Failed\", \"Finished\", \"Running\"]\r\n\r\nRawSeries = from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|all_job_steps|finished_job_steps|completed_job_steps|failed_job_steps|running_job_steps/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Order\":r.name, \"Time\":r._time, \"All\":r.all_job_steps, \"Completed\":r.completed_job_steps, \r\n          \"Failed\":r.failed_job_steps, \"Finished\": r.finished_job_steps, \"Running\":r.running_job_steps}))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()",
     "rawSql": "SELECT\n  processing_order.identifier AS order_identifier, \n  mon_order_state.name AS state, \n  all_job_steps AS all, \n  failed_job_steps AS failed, \n  finished_job_steps AS finished, \n  completed_job_steps AS completed, \n  running_job_steps AS running, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nINNER JOIN mon_order_state on processing_order_mon_order_progress.mon_order_state_id = mon_order_state.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC')  \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Running Job Steps (${var_processing_order})",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|running_job_steps/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")",
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   running_job_steps\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Finished Job Steps (${var_processing_order})",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"order\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"progress\"and r._field =~ /name|finished_job_steps/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.name == \"${var_orders}\")",
     "rawSql": "SELECT\n   datetime at TIME zone 'UTC' AS \"time\",\n   finished_job_steps\nFROM processing_order_mon_order_progress\nINNER JOIN processing_order on processing_order_mon_order_progress.processing_order_id = processing_order.id\nWHERE\n  $__timeFilter(datetime at TIME zone 'UTC') AND \n  processing_order_mon_order_progress.processing_order_id = (SELECT id FROM processing_order WHERE identifier = '${var_processing_order}')\nORDER BY datetime"
    }
   ]
  }
 ]
}