{
 "title": "Services",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "var_service",
    "label": "Services",
    "query": "SELECT mon_service.name\nFROM mon_service_state_operation\nINNER JOIN mon_service on mon_service_state_operation.mon_service_id = mon_service.id\nWHERE $__timeFilter(mon_service_state_operation.datetime at TIME zone 'UTC')\nGROUP BY 1; \n\n\n"
   }
  ]
 },
 "panels": [
  {
   "title": "${var_service} (selected)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = '${var_service}') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "$var_service (selected)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='$var_service') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='$var_service') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "${var_service} (selected)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"${var_services}\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = '${var_service}') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "${var_service} (selected)",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"Service\", \"State\" ]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n\n \n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = '${var_service}') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Facility Manager",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"facility_manager\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Facility Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Facility Manager",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Facility Manager') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Facility Manager') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "Facility Manager",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"facility_manager\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Facility Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "All",
   "type": "table",
   "gridPos": { "h": 48, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"Service\", \"State\" ]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n\n \n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service.name AS service,\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nINNER JOIN mon_service on mon_service_state_operation.mon_service_id = mon_service.id\nWHERE  \n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"facility_manager\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Grafana') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Grafana') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Grafana') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"facility_manager\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Grafana') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "GUI",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"facility_manager\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'GUI') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "GUI",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='GUI') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='GUI') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "GUI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"facility_manager\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'GUI') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Ingestor",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"facility_manager\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Ingestor') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Ingestor",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Ingestor') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Ingestor') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "Ingestor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"facility_manager\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Ingestor') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Metadata Database",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"order_manager\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE\n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Metadata Database') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Metadata Database",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Metadata Database') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Metadata Database') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "Metadata Database",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"order_manager\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE\n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Metadata Database') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Order Manager",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"facility_manager\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Order Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Order Manager",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Order Manager') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Order Manager') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "Order Manager",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"facility_manager\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Order Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "PRIP API",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"planner\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'PRIP API') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "PRIP API",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='PRIP API') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='PRIP API') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "PRIP API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"planner\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'PRIP API') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Processor Manager",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"facility_manager\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Processor Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Processor Manager",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Processor Manager') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Processor Manager') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "Processor Manager",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"facility_manager\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Processor Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Product Class Manager",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"facility_manager\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Product Class Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Product Class Manager",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Product Class Manager') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Product Class Manager') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "Product Class Manager",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"facility_manager\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Product Class Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Production Planner",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"facility_manager\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Production Planner') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Production Planner",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Production Planner') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Production Planner') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "Production Planner",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"facility_manager\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Production Planner') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Storage Manager",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"facility_manager\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Storage Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Storage Manager",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Storage Manager') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='Storage Manager') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "Storage Manager",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"facility_manager\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Storage Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "User Manager",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 50 },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"facility_manager\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'User Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "User Manager",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='User Manager') AND\r\n    mon_service_state_id = (SELECT id FROM mon_service_state WHERE name='running') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n\r\n  / (SELECT\r\n    COUNT(*)  \r\n  FROM\r\n    mon_service_state_operation\r\n  WHERE\r\n    mon_service_id = (SELECT id FROM mon_service WHERE name='User Manager') AND\r\n    $__timeFilter(datetime at TIME zone 'UTC'))::decimal\r\n  * 100;"
    }
   ]
  },
  {
   "title": "User Manager",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\" ]\r\n\r\nRawSeries =from(bucket: \"operation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.service == \"facility_manager\")\r\n\r\nNamedSeries = RawSeries\r\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\r\n    |> keep(columns:FinalOutput)\r\n    \r\nNamedSeries |> yield()\r\n",
     "rawSql": "SELECT \n  datetime at TIME zone 'UTC' AS \"time\",\n  mon_service_state.name AS state\nFROM mon_service_state_operation\nINNER JOIN mon_service_state on mon_service_state_operation.mon_service_state_id = mon_service_state.id\nWHERE \n  mon_service_state_operation.mon_service_id = (SELECT id FROM mon_service WHERE name = 'User Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  }
 ]
}