{
 "title": "Services per month",
 "time": { "from": "now-24M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "var_service",
    "label": "Services",
    "query": "SELECT mon_service.name\nFROM mon_service_state_operation\nINNER JOIN mon_service on mon_service_state_operation.mon_service_id = mon_service.id\nWHERE $__timeFilter(mon_service_state_operation.datetime at TIME zone 'UTC')\nGROUP BY 1; \n\n\n"
   }
  ]
 },
 "panels": [
  {
   "title": "${var_service} (selected)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = '${var_service}') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "$var_service (avg - selected)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='$var_service') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "${var_service} (selected)",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"Service\", \"State\" ]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n\n \n",
     "rawSql": "SELECT \n  ROUND(up_time::numeric, 2) AS \"Up Time\", \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = '${var_service}') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Facility Manager",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Facility Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Facility Manager",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='Facility Manager') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "All",
   "type": "table",
   "gridPos": { "h": 60, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"Service\", \"State\" ]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"Service\":r.service, \"State\":r.state, }))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n\n \n",
     "rawSql": "SELECT \n  ROUND(up_time::numeric, 2) AS \"Up Time\", \n  mon_service.name AS \"Service\",\n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nINNER JOIN mon_service ON mon_service.id = this.mon_service_id\nWHERE \n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Grafana') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='Grafana') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "GUI",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'GUI') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "GUI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='GUI') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "Ingestor",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Ingestor') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Ingestor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='Ingestor') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "Metadata Database",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Metadata Database') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Metadata Database",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='Metadata Database') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "Order Manager",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Order Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Order Manager",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='Order Manager') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "PRIP API",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'PRIP API') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "PRIP API",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='PRIP API') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "Processor Manager",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Processor Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Processor Manager",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='Processor Manager') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "Product Class Manager",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Product Class Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Product Class Manager",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='Product Class Manager') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "Production Planner",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Production Planner') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Production Planner",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='Production Planner') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "Storage Manager",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'Storage Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Storage Manager",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='Storage Manager') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  },
  {
   "title": "User Manager",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "FinalOutput = [\"Time\", \"State\"]\n\nRawSeries =from(bucket: \"operation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"service_state\" and r._field =~ /state|service/ )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.service == \"${var_services}\")\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({\"Time\":r._time, \"State\":r.state}))\n    |> keep(columns:FinalOutput)\n    \nNamedSeries |> yield()\n",
     "rawSql": "SELECT \n  up_time, \n  datetime at TIME zone 'UTC' AS \"time\"\nFROM mon_service_state_operation_month this\nWHERE \n  this.mon_service_id = (SELECT id FROM mon_service WHERE name = 'User Manager') AND\n  $__timeFilter(datetime at TIME zone 'UTC') \nORDER BY datetime"
    }
   ]
  },
  {
   "title": "User Manager",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  AVG(up_time) \r\nFROM  \r\n  mon_service_state_operation_month \r\nWHERE \r\n  mon_service_id = (SELECT id FROM mon_service WHERE name='User Manager') AND \r\n  $__timeFilter(datetime at TIME zone 'UTC')"
    }
   ]
  }
 ]
}